### ISSUE TITLE
Conditional Validation 

### ISSUE THREAD

**Issue by phillirodney** [jaredpalmer/formik#1065]
### As a developer I want to trigger different validation functions corresponding to different drop down options in my form

 i.e. if address is chosen from the dropdown and an address is written in the next form field (this being being mapped as a type of address), the address validator will run and so on for Car and Name

private validateFields = (values: CreateUserValues) => {
    return doValidation(values, {
	  value: this.isName(values.type)
        ? [requireField, lengthValidation]
        : [requireField],
        value: this.isAddress(values.type)
        ? [requireField, addressValidation]
        : [requireField],
      value: this.isCar(values.type)
        ? [requireField, carValidation]
        : [requireField],
   });
  };

Error:

[ts] An object literal cannot have multiple properties with the same name in strict mode.
[ts] Duplicate identifier 'value'.

**Comment by weyert** [comment]
You could consider using a schema? 
For example:

```
export const SignUpSchema = Yup.object().shape({
hasSignAuthority: Yup.boolean().when('$currentStep', {
            is: 3,
            then: Yup.boolean()
                .required()
                .oneOf([true], 'Agreement needs to be accepted'),
            otherwise: Yup.boolean().notRequired(),
        }),
})
```

Here the field `hasSignAuthority` is only required when the context `$currentStep` is 3 if not it won't be required yet. You could use `type` instead of `$currentStep` in your case. See also:
https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema
