### ISSUE TITLE
How to update values from a FieldArray onChange

### ISSUE THREAD

**Issue by jordantrainor** [jaredpalmer/formik#1136]
## ❓Question

I'm wondering how to update values when using a FieldArray. I have the values coming through, but how to I make onChange work?

Thank you.

**Comment by Evanion** [comment]
same here...
example project: https://codesandbox.io/s/ox047lvn4y

**Comment by malydok** [comment]
@Evanion You should probably set the value using `setFieldValue` when using custom fields so `form.setFieldValue(field.name, value)` in your case.

I have the same issue as OP though, because you can't set FieldArray values with `setFieldValue`, it doesn't parse the `field` parameter (which it could using `_.get` and `_.set`). Looking into the source to find a solution if possible.

**Comment by jaredpalmer** [comment]
You should use setFieldValue.

**Comment by olelivalife** [comment]
I cant get this to work
