### ISSUE TITLE
Should a change event mark the value as touched?

### ISSUE THREAD

**Issue by alexanbj** [jaredpalmer/formik#114]
Some background:
I have a form where I validate on change, and use the isValid prop to control whether the submit button is enabled or disabled.

The problem for me is that isValid is computed based on the dirty values, and a field isn't considered touched/dirty until a blur happens. I want the submit button to be enabled as soon as the form is in valid state, even while typing. Right now this doesn't happen until an input loses focus.

This feels weird to me. validateOnChange gives me the impression that it in some way should have a say over the isValid prop.

This would be fixed by marking a value as touched when an onChange happens, which makes sense to me at least. While typing, I am definitely "touching" it.

I could provide a pull request for this if you are interested.

And finally, thank you so much for this great library!

**Comment by jaredpalmer** [comment]
Pass `validateOnChange: true` and `validateOnBlur: false` to your form’s options

**Comment by alexanbj** [comment]
@jaredpalmer this doesn't help in my case.

I forked the codesandbox example to illustrate this: https://codesandbox.io/s/xGw0KRZ6E

As you can see, the submit button is disabled while the form is invalid (the isValid prop). 
The submit button won't be enabled until I blur the field, even though you've typed in a valid email address. After the first blur, it works as expected, because the field is then touched.

Would you be willing to reopen this issue?

**Comment by skattyadz** [comment]
We've hit this problem too.

A form becomes dirty if a field has been touched, not if a field has been changed. If a field is dirty, `isValid` uses the data in `values`. If it's not dirty it uses `isInitialValid`

In forms with a single field and `validateOnChange`, the field gets changed before there's been a blur event, so the form isn't yet dirty and formik doesn't look at the value when calculating `isValid`

We hacked around this with 
```js
handleChange={(...args) => {
  handleChange(...args);
  handleBlur(...args);
}}
```

Should the definition of dirty be changed? I'd expect a form to be dirty once the first change is made

**Comment by jaredpalmer** [comment]
@skattyadz feel free to submit a PR on this

**Comment by jaredpalmer** [comment]
I think this (and some other edge cases) can be fixed with adding touchOnChange and touchOnBlur options

**Comment by eonwhite** [comment]
We don't want a change event to mark the field as `touched` because then you would have validation errors appear while in the process of typing initial input into an empty field, which is bad UX.

We could separate the concept of `touched` and `dirty` and have the latter get set onChange and not the former, but that feels confusing.

I think instead we should store the result of the most recent validation in form state, and isValid() can just check that. If there has not been a validation yet, it can use isInitialValid.

**Comment by criles25** [comment]
I ran into this issue, and I solved it by passing the `handleBlur` function to the `onInput` event handler. For example,

```
<input
  ...
  onInput={handleBlur}
  ...
/>
```

^ will set the status of that input to `touched` as soon as the user enters something.

Also, checkout the list of events in the react docs: https://reactjs.org/docs/events.html#touch-events.

**Comment by chenjianjx** [comment]
Seems that these 2 added options were finally removed?  In my opinion, they are very useful.

**Comment by chenjianjx** [comment]
> We don't want a change event to mark the field as `touched` because then you would have validation errors appear while in the process of typing initial input into an empty field, which is bad UX.

Well, IMO lots of people like this kind of UX, and dislike that a field is not validated until blurred.  Can we have this as an option?

**Comment by shaungc-su** [comment]
I second what @chenjianjx mentioned which provides a realtime feedback experience.

Another thing is I noticed `dirty` will get set to `true` upon focus, which is actually what I imagine `touched` to behave at first. Now I realize formik only sets touched after `onBlur`, where you need to go through focus -> unfocus in order to trigger this - the first time you "touched" / focus the input does not set `touched` to true.

Looks like currently `dirty` only reflects on a form-level. Would be great if `dirty` can be set up at field-level.

**Comment by farzanfx** [comment]
> > We don't want a change event to mark the field as `touched` because then you would have validation errors appear while in the process of typing initial input into an empty field, which is bad UX.
> 
> Well, IMO lots of people like this kind of UX, and dislike that a field is not validated until blurred. Can we have this as an option?

I came up with a solution after a few days of research.
I used "use-debounce" package to make a better UX during development by using `useFormik` hook because i have another react hook context manager to make multi step sign up form.
the thing is that on my input `onChange ` listener I added another handler called `touchTitle` using `useDebouncedCallback` from `use-debounce`. by calling this event handler i manually make my `title` `touch` status to `true`.
here's what I did:

```
// importing debounce to call a function with delay
import { useDebouncedCallback } from 'use-debounce';
```

```
// its not get title input touched immediately, but only when you stop typing after 1000ms
// if user start typing again before 1000ms ends, the callback timer will renew without dispatching
const touchTitle = useDebouncedCallback(() => formik.touched.title = true, 1000);
```

```
return (
<TextField
    id="title"
    name="title"
    error={formik.touched.title && formik.errors.title ? true : false}
    helperText={formik.touched.title && formik.errors.title
        ? formik.errors.title
        : "something is wrong."}

    onBlur={(e) => formik.handleBlur(e)}

    onChange={(e) => {
        formik.handleChange(e)
        touchTitle.callback(e);
        // formik.
        setFormData(e)
    }}
    value={title}
  />
<Button disabled={formik.isValid ? false : true} onClick={(e) => nextHandler(e)  } color="primary" variant="contained" fullWidth>
        sign up
</Button>
)
```
Also the code above is great solution for `async` form validations, which means instead of sending requests on every key change  you can make `async` form validation after user stop typing in.

Right or wrong its really work for me, and I believe `formik ` really needs to add such a functionality to its core and make developers life much easier.
