### ISSUE TITLE
FieldProps contain only field and form props, but misses any other props passed to field

### ISSUE THREAD

**Issue by Verbon** [jaredpalmer/formik#1250]
## 🐛 Bug report

The [docs states](https://jaredpalmer.com/formik/docs/api/field#field-render-props):

`Field`'s render props are an object containing:

- field: An object containing onChange, onBlur, name, and value of the field
- form: The Formik bag.
- **Any other props passed to field**

### Current Behavior

`Field`'s render props contain only field and form props, it **misses any other props passed to field, if used via `render` or `children` props**.
It actually affects both `Field` and `FastField`.

### Expected behavior

`Field`'s and `FastField`'s render props should also contain any other props passed to field in all implementations, even when used via `render` or `children` props.

### Reproducible example

Please, see this sample: https://codesandbox.io/s/pynqnq2z4m. Please note, that `custom` props object is always empty, and it does not contain `myCustomProps` field.

### Suggested solution

Current `Field` and `FastField` render method implementation should be changed in the way, so they pass down any other props passed to them, regardless of the way they are used.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.2 |

**Comment by jaorsh** [comment]
+1 I've run into this issue too. The basic use-case being passing a `theme` prop to a custom react component like `<Field component={myCustomInput} theme='light' />`. Custom props are not available on `<Field />` (whether render, children or component based render props). 

One unsuccessful workaround was to use (https://jaredpalmer.com/formik/docs/api/formik#status-any)[status object] however the Field component does not seem to have access. 

Perhaps a maintainer can weigh in on if this is a bug or by design?

Related workaround? https://github.com/jaredpalmer/formik/issues/1239

**Comment by redgenie** [comment]
You should use `component` rather than `render` if you want to get all the other props.

**Comment by Verbon** [comment]
@jaredpalmer why this won't fix? It's not meant to be used the described way via `render` (and the docs are actually lying) or it's not technically impossible?

**Comment by jaredpalmer** [comment]
The docs are wrong. We should clarify. This only true for component. It mimics react router. There is no need to pass them through for children and and render because all would-be prop values are in scope.

**Comment by jaredpalmer** [comment]
Sorry for brevity, I am on my phone. We should open a PR to clarify the docs for Field
