### ISSUE TITLE
Field's Formik bag empty when nested in third party component

### ISSUE THREAD

**Issue by mellis481** [jaredpalmer/formik#1269]
I'm using Formik's `Field` component to render an input like this:
```
<Formik 
  initialValues={initialValues}
  onSubmit={onSubmit}
  render={formProps => (
    <Form>
      <Field name="lastName" render={({ field, form }) => (
        <input {...field} placeholder="lastName" />
      )} />
    </Form>
)} />
```
In the code above, Formik seems to be "automagically" determining the Formik bag `form` object in the `Field`'s `render` function.

This has worked without issue until I integrated my `Field` into a third party library, in my case, rendering it in a cell of an agGrid table.  When I do this, I get _TypeError: this.props.formik.registerField is not a function_ browser console errors.  Debugging this error, I see the following in Formik's compiled code:

```
FieldInner.prototype.componentDidMount = function () {
  this.props.formik.registerField(this.props.name, this);
};
```
When I inspect `this.props.formik` which should be my Formik bag, it's an empty object.  This is the same object I see when I put my break point in the `Field`'s `render` function.  When I inspect this object for instances of my `Field` outside of agGrid, it is the fully populated Formik bag including `initialValue` props, `registerField` function, etc.

**Why is Formik not properly retrieving the Formik bag `form` object when my `Field` is nested in an agGrid table cell and how can I address this issue?**

**Comment by mellis481** [comment]
I created a working [CodeSandbox](https://codesandbox.io/s/0w97oqjjl) example.

**Comment by jaredpalmer** [comment]
Formik's `<Field>` does not implement the Cell Renderer API of the library you are using. I'm not sure why Formik's context is not defined inside of the data grid, but my guess is that the library does not use React under the hood. 

My suggestion is for you to instead implement your Cell Renderer on your own with Formik's `setFieldValue`.

Docs: https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean-void

FWIW you are treating each and every cell in your agGrid as a separate input. There may be far better APIs/ways of getting the data out of agGrid once it is changed, but I'm not sure. You'll have to figure that out yourself.

**Comment by VehpuS** [comment]
> I created a working [CodeSandbox](https://codesandbox.io/s/0w97oqjjl) example.

I used your code sandbox as a starting point to create a working example of an integration of formik with ag-grid: https://codesandbox.io/s/yvvwwvl4xv

As @jaredpalmer said, the issue in your code was indeed with the ag-grid end: ag-grid  does not use the react context API - https://github.com/ag-grid/ag-grid/issues/2838 - and was therefore not able to pass it to the Field component in your renderer.

What I did instead was pass the formik bag's relevant props through ag-grid's context (https://www.ag-grid.com/javascript-grid-context/) and used it in the component (which I made into a cell editor, but you should be able to just use the renderer if you prefer.

The last thing I had to do was handle an internal state for the renderer and only update on blurs. I did this because otherwise I would lose focus from the input on each keystroke. I suspect this is because each change of context at the grid level caused the whole grid (or at least the cell editor) to redraw. I'm not sure how that can be mitigated ATM, but at least in my use case I suspect onBlur changes will be more than enough.

Hope this helps :).

**Comment by VehpuS** [comment]
After some more thinking - I think this is in fact the "correct" way to go about things:
https://codesandbox.io/s/vv21n7v4nl

Rather than customize a cell renderer - I use ag-grid's edit callback to update the formik field. This requires almost no code beyond the basic formik / ag-grid apis (and should still work if / when you require custom editing components without having to manage their internal state or getting formik to update from them). This also doesn't refresh the whole grid on each refresh - a definite plus :).

**Comment by VehpuS** [comment]
Made a fix to the last sandbox - I can't rely on ag-grid's row order (as grids can be sorted and data can be filtered) so I add a row index to the data as a hidden field to use as an array index.
