### ISSUE TITLE
Does validating the form with multiple inputs trigger a re render for each validation?

### ISSUE THREAD

**Issue by Nemsae** [jaredpalmer/formik#1289]
## ❓A Clarification Question

I have 7 inputs on a form with validation that are required. When I call `handleSubmit` with an empty form (all inputs pristine) my form re renders 7 times. 

I'm assuming what happens is that validation is run sequentially? The first input validates, component re renders. Second input validates, component re renders, etc. 

Is my assumption correct? And if so are there any workarounds to prevent all these re renders?

**Comment by jaredpalmer** [comment]
`isSubmitting` and `isValidating` are toggled [(more info)](https://jaredpalmer.com/formik/docs/guides/form-submission), and because these live on Formik context, and `<Field>` connects to context, it renders when Formik context changes. You can prevent/optimize this behavior using [`shouldComponentUpdate`](https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action) (just like you would with any other React component).
