### ISSUE TITLE
FastField does not avoid re-renders

### ISSUE THREAD

**Issue by nfantone** [jaredpalmer/formik#1320]
### Current Behavior

Using `FastField` components, changes on other fields end up re-rendering the whole form, including other `FastField`s.

Here's a demonstration running the [documentation example](https://github.com/jaredpalmer/formik/blob/master/docs/api/fastfield.md), where "First Name" is a `FastField` and "Email" is a regular `Field`.

- **Updates to "First Name" (`FastField`)**

![](http://g.recordit.co/bANo2mux15.gif)

- **Updates to unrelated regular `Field`**

![](http://g.recordit.co/msWCNh8yLR.gif)

> Additionally, the code snippet in docs above does not compile as-is: it's accessing an undeclared `form` variable in the `render` method of `Formik`.

### Expected behavior

Changes on a `Field` should not trigger re-renders of unrelated `FastField`s.

### Reproducible example

https://codesandbox.io/s/nrzq1vv1p
(a simple, amended copy-paste of example from docs).

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | `1.4.3`
| React            | `16.7.0`
| TypeScript       | -
| Browser          | Chrome `72.0.3626.96`
| npm/Yarn         | `yarn` `1.13.0`
| Operating System | macOS 10.14.2 (18C54)

**Comment by jaredpalmer** [comment]
Updates from `<FastField>` will trigger rerenders of `<Field>`

**Comment by jaredpalmer** [comment]
This is the desired behavior of `<Field>`. Maybe, I am just missing the bug here.

**Comment by jaredpalmer** [comment]
`<FastField>` implements shouldComponentUpdate, `<Field>` does not, but they both read from the same context. Therefore changes made to the context via `<FastField>` will _always_ be available to `<Field>`, but changes to made by a `<Field>` will not be made available to a `<FastField>`.

**Comment by carlosagsmendes** [comment]
@nfantone I'm just getting started with Formik and was under the same impression. But the highlight updates can be misleading since you have to consider the component tree.

After using the profiler, I think FastField is doing its job: 

- there seems to be a wrapper around FastField, and that wrapper is always rendered
- but the FastFieldInner component is not re-rendered, even when we type into a regular Field (I typed a single character in the _Lastname_ field) :

<img width="1343" alt="sandbox - codesandbox 2019-02-08 23-06-26 1" src="https://user-images.githubusercontent.com/1224078/52511120-9861b480-2bf6-11e9-8ff7-228148e5f81e.png">

One thing that I'm not understanding is why do we get 4 commits in the profiler. It seems to be related to validation. Here's the data for _FirstName_ (FastField):

<img width="862" alt="sandbox - codesandbox 2019-02-08 23-14-00 1" src="https://user-images.githubusercontent.com/1224078/52511354-7c124780-2bf7-11e9-9688-366adb7d56c1.png">

<img width="859" alt="sandbox - codesandbox 2019-02-08 23-14-28 1" src="https://user-images.githubusercontent.com/1224078/52511355-7c124780-2bf7-11e9-9a7d-860d7b9fe331.png">

<img width="861" alt="sandbox - codesandbox 2019-02-08 23-14-51 1" src="https://user-images.githubusercontent.com/1224078/52511357-7c124780-2bf7-11e9-81be-82352d234f92.png">

<img width="856" alt="sandbox - codesandbox 2019-02-08 23-15-10 1" src="https://user-images.githubusercontent.com/1224078/52511358-7c124780-2bf7-11e9-8f50-ae511afb36ec.png">

The **isValidating** prop changed twice, and that seems to be the reason of the 4 commits reported by the profiler. 

Is it expected for the validation to run twice? 

Thanks

**Comment by nfantone** [comment]
> Updates from `<FastField>` will trigger rerenders of `<Field>`

@jaredpalmer Perhaps I am the one missing something - but if you take a look at the GIF examples, you'll see that the opposite scenario takes place: _changes to `Field` trigger re-renders on `FastField` inputs_. That's what's unexpected there.

**Comment by carlosagsmendes** [comment]
I created a codesandbox that displays a render counter for each field and uses up to date versions of React and Formik. [You can try it here](https://codesandbox.io/s/wnkp6y78y5)

I think the behaviour is right since when you type in the FastField input, both fields are re-rendered. But when you type in the Field input the FastField input is not re-rendered:

#1 When I type 'hello' in the FastField both fields are rendered 5 times

<img width="468" alt="sandbox - codesandbox 2019-02-08 23-44-47" src="https://user-images.githubusercontent.com/1224078/52512302-09f03180-2bfc-11e9-8253-9ec691d68bbf.png">

#2 When I type 'hello' in the Field, only the field is rendered 5 times

<img width="470" alt="sandbox - codesandbox 2019-02-08 23-45-03" src="https://user-images.githubusercontent.com/1224078/52512303-0a88c800-2bfc-11e9-8e6f-bcf8cb928a14.png">

The profiler confirms that **FastFieldInner** and  **Input** controls for the FirstName FastField are not rendering when we type in the LastName Field:     

<img width="1216" alt="sandbox - codesandbox 2019-02-08 23-47-37 1" src="https://user-images.githubusercontent.com/1224078/52512304-0a88c800-2bfc-11e9-9fa0-c9ced02587d0.png">

I don't understand the 4 commits shown by the profiler with a single keystroke as mentioned above... So I'm not sure if it is expected or if it can be further optimized.

**Comment by nfantone** [comment]
@carlosagsmendes That is interesting and informative. Thanks so much for putting all of that together.

I understand `FastField` behaviour better now - although I was expecting it to not re-render at all, which is *not* exactly the case, as it turns out. The outer wrapper `FormikConnect(FastFieldInner)` gets rendered every time the `Field` re-renders. And those where the update highlights that you can see in my original example.

**Comment by carlosagsmendes** [comment]
Thank you @nfantone, if you want to dig deeper I've added [why-did-you-update](https://github.com/maicki/why-did-you-update) to the Codesandbox:

<img width="1067" alt="formik codesandbox template - codesandbox 2019-02-11 22-17-10" src="https://user-images.githubusercontent.com/1224078/52597490-fbe42000-2e4a-11e9-98bb-7dfa264b8ff2.png">

Now you can see what is triggering the renders in the console.

**Comment by nfantone** [comment]
@carlosagsmendes From what you have put together (awesome job, BTW), I can see loads of warnings such as:

```sh
FormikConnect(FastFieldInner).props: Value did not change. Avoidable re-render!
```

Or:

```sh
FormikConnect(FastFieldInner).state: Value is the same (equal by reference). Avoidable re-render!
```

This is in line with what I'm seeing in the default [implementation of `shouldComponentUpdate` on `FastFieldInner`](https://github.com/jaredpalmer/formik/blob/master/src/FastField.tsx#L115). Seems like updating logic is entirely based on `props.formik` rather than the actual values of the incoming props. I believe those re-renders could be avoided simply by comparing old and new props directly. (cc. @jaredpalmer).

**Comment by nfantone** [comment]
Ok, follow up here.

After closer inspection, I realised that all re-renders were being caused by the `connect` HoC. Wrapping [the component it returns](https://github.com/jaredpalmer/formik/blob/master/src/connect.tsx#L18) in `React.memo` makes all [why-did-you-update](https://github.com/maicki/why-did-you-update) warnings go away.

**Comment by nfantone** [comment]
@jaredpalmer Why close this? We've shown there's room for improvement here and `FastField` does not avoid all re-renders.

**Comment by zaguiini** [comment]
Same problem. I don't get it...

**Comment by tomekrozalski** [comment]
For me it is obvious imperfection. `RenderFunction` (`<Formik render={() => RenderFunction} />`) always re-renders, I mean always when `values`, `touched`, `errors` etc. change. And we cannot memoize it (I mean wrap in `React.memo`). I have a hack for it: I make `RenderFunction` return another component (`<AnotherComp {...props} />`) which is wrapped in `React.memo`. That is how I prevent whole-form re-renders. But still I don't get why I cannot memoize `RenderFunction`...

**Comment by taneba** [comment]
@nfantone 
https://codesandbox.io/s/4w6lozp1vw
I've found a interesting workaround for this issue. 
What I did here is move `<label>` inside of the FastField's render, then it doesn't rerender by updates on the other Fields.

**Comment by markchkhotua** [comment]
> I created a codesandbox that displays a render counter for each field and uses up to date versions of React and Formik. [You can try it here](https://codesandbox.io/s/wnkp6y78y5)
> 
> I think the behaviour is right since when you type in the FastField input, both fields are re-rendered. But when you type in the Field input the FastField input is not re-rendered:
> 
> #1 When I type 'hello' in the FastField both fields are rendered 5 times
> 
> <img alt="sandbox - codesandbox 2019-02-08 23-44-47" width="468" src="https://user-images.githubusercontent.com/1224078/52512302-09f03180-2bfc-11e9-8253-9ec691d68bbf.png">
> 
> #2 When I type 'hello' in the Field, only the field is rendered 5 times
> 
> <img alt="sandbox - codesandbox 2019-02-08 23-45-03" width="470" src="https://user-images.githubusercontent.com/1224078/52512303-0a88c800-2bfc-11e9-8e6f-bcf8cb928a14.png">
> 
> The profiler confirms that **FastFieldInner** and **Input** controls for the FirstName FastField are not rendering when we type in the LastName Field:
> 
> <img alt="sandbox - codesandbox 2019-02-08 23-47-37 1" width="1216" src="https://user-images.githubusercontent.com/1224078/52512304-0a88c800-2bfc-11e9-9fa0-c9ced02587d0.png">
> 
> I don't understand the 4 commits shown by the profiler with a single keystroke as mentioned above... So I'm not sure if it is expected or if it can be further optimized.

Hi. I tried your code in my app, but it still re-renders everything. Can it be connected with some props that are passed to form component or how I export it, etc?

First I was trying to implement FastField in my form, it was not working, then I deleted everything and pasted your code - it still don't work

`
import React from 'react';
import {FastField, Field, Formik, Form} from 'formik';

class Input extends React.Component {
    constructor(props) {
        super(props);
        this.renders = 0;
    }

    render() {
        const {field, form, ...rest} = this.props;
        return (
            <div>
                <input {...field} {...rest} />
                <p># of renders: {this.renders++}</p>
            </div>
        );
    }
}

class Test extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <Formik
                initialValues={{firstName: '', lastName:''}}
                // validationSchema={validationSchema}
                onSubmit={()=>{}}
                render={formikProps => (
                    <Form>
                        {/** This <FastField> only updates for changes made to
                         values.firstName, touched.firstName, errors.firstName */}
                        <label htmlFor="firstName">First Name (FastField)</label>
                        <FastField name="firstName" placeholder="" component={Input} />
                        <label htmlFor="lastName">Last Name (Field)</label>
                        <Field name="lastName" placeholder="" component={Input} />
                        <button type="submit">Submit</button>
                    </Form>
                )}
            />
        );
    }
}

export default Test;

`
![image](https://user-images.githubusercontent.com/4004333/69810227-188fef80-11f4-11ea-9e31-bca86f6587da.png)

**Comment by yashinshekh** [comment]
same problem

**Comment by FilmCoder** [comment]
I've been having problems with FastField, on Formik `2.1.4.`  Changes from other Fields will force rerenders of all FastFields.  I made this HOC which takes a normal input (only tested with text or textarea) and wires it up to Formik in a debounced manner.  Essentially, when the input is focused and the user is typing, it becomes an uncontrolled component, and every few seconds it syncs back up to the main formik value store by executing change handlers.  When it's not in focus, the input acts as a normal controlled component.

```/**
 * HOC that takes an input and gives it debounced onChange behavior.
 * 
 * This works by internally managing the value of the input, and every
 * so often communicating the updated value to formik via formik.handleChange
 * in a debounced manner.  This prevents lag on the form, because 
 * formik.handleChange will force a rerender of every input in the entire
 * form.  Normally this would be solved by Formik's built-in FastField, but
 * FastField is currently broken in Formik 2.x.
 * 
 * @param {*} WrappedInput input to debounce, must be TextArea or TextInput
 */
const debounceInput = (WrappedInput) => {
    return props => {
        const formik = useFormikContext();
        const [focused, setFocused] = useState(false);
        const [value, setValue] = useState(undefined);
        const debouncedHandleChange = useRef(_.debounce(formik.handleChange, 1000, {maxWait: 5000}));
        let newProps = {...props};
        const { name } = props;
    
        assign(newProps, {
            value: focused ? value : formik.values[name],
            onChange: e => {
                setValue(e.target.value);
                debouncedHandleChange.current(e)
            },
            onFocus: e => {
                setFocused(true);
                setValue(formik.values[name])
            },
            onBlur: e => {
                setFocused(false);
                formik.handleBlur(e);
            },
        })
    
        return <WrappedInput {...newProps}/>
    }
}
