### ISSUE TITLE
onChangeValues callback

### ISSUE THREAD

**Issue by guilhermedecampo** [jaredpalmer/formik#143]
Hi @jaredpalmer!

Is there any reason to not have an `onChangeValues` callback on formik where I can receive the props `values` of the form?

Best,

**Comment by skattyadz** [comment]
Can you give a use case? You should be able to achieve this with `componentWillReceiveProps` in the wrapped component, but I'm interested in whether you're doing somewhere where that doesn't fit

**Comment by jaredpalmer** [comment]
Agreed. Curious about use case here. 

@guilhermedecampo Can you elaborate on what you are trying to accomplish?

**Comment by guilhermedecampo** [comment]
Hi guys!

Yeah @skattyadz I used the `componentWillReceiveProps` for now. just wondering/asking if would be nice to have already in the component.. 🤔 

Use case:

We are developing an RN application which is necessary to change routes to fill up the form. 
Imagine a full page select list. If user made some modification we need to save it somewhere before send it to the server. 

Thanks guys.

**Comment by skattyadz** [comment]
Thanks for the follow up. Here are my thoughts for the thread and @jaredpalmer:

1) How much of a problem is it? Do other people have the same problem? Can it be solved with better documentation?
2) What's the ultimate conclusion of this change? If we add `onChangeValues` should we add `onChangeIsValid` and `onChangeErrors` and [...]. Is the answer a single `onChange` which includes all of those? Do we need to include the previous values so that you can see what was changed?

Formik's strength is that it allows you to achieve whatever you need without a complex API or complexity inside the library. If many people are rewriting the same behaviours then that's boilerplate; and we should decide when those should be accommodated or when that's perfectly ok

**Comment by jaredpalmer** [comment]
React has lifecycle events just for this exact thing: componentDidUpdate or componentWillReceiveProps if you need to setState. Just use the framework here.

**Comment by skattyadz** [comment]
Another approach to the same problem: Are there HOCs we can recommend (or provide) that would solve common needs like this?

Taking inspiration from modules like:
https://www.npmjs.com/package/@hocs/with-callback-on-change
https://www.npmjs.com/package/map-props-changes-to-callbacks

**Comment by pselden** [comment]
Dumb question, but is there any way to do this when using the "render" style forms?
