### ISSUE TITLE
Getting empty formik bag when wrapping with connect()

### ISSUE THREAD

**Issue by puru0019** [jaredpalmer/formik#1462]
### Current Behavior

**Getting empty formik object when wrapping my component with connect**

![image](https://user-images.githubusercontent.com/23036485/56655147-919ff500-66af-11e9-81b4-da33cf329f59.png)

### Expected behavior

Should get formik properties when wrapping connect around my component

### Reproducible example

```
import React from 'react';
import { connect, getIn } from 'formik';

// This component renders an error message if a field has
// an error and it's already been touched.
const ErrorMessage = props => {
  console.log(props)
  // All FormikProps available on props.formik!
  const error = getIn(props.formik.errors, props.name);
  const touch = getIn(props.formik.touched, props.name);
  return touch && error ? error : null;
};
export default connect(ErrorMessage)
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^1.5.1
| React            |^16.8.1
| TypeScript       |
| Browser          |Chrome
| npm/Yarn         |npm
| Operating System |windows 10

**Comment by ryanburr** [comment]
I was running into this same issue, but after a little debugging I noticed I had 2 copies for `formik.esm.js` loaded (something wrong I was doing on my end). The first copy is the one with the full formik bag that my form initialized with. The second copy is the one that was connecting to my component which did not include the initialized form. Once I fixed the issue of loading 2 copies, this issue was resolved.

**Comment by puru0019** [comment]
How did you fix the issue. Can you provide with some example?

**Comment by spawluk** [comment]
I was able fix that using <Field component={connectedCoponent}>

**Comment by ryanburr** [comment]
I had 2 copies of Formik loaded because I had it as a peer dependency in a library I was developing. When I `npm link`'ed the library in an application I was doing work in, I wound up with 2 versions of Formik. 

I have since removed this as a peer dep in my library and made it a regular dependency. Another workaround would have been to specify an alias in my webpack config of my **application** to resolve to the same version of Formik.

```javascript
{
  resolve: {
    alias: {
      formik: path.resolve(path.join(__dirname, './node_modules/formik')
    }
  }
}
```

My use case is not an issue with formik, it is an issue with the way `npm link` resolves dependencies.

**Comment by johnrom** [comment]
@puru0019 were you able to determine whether you had loaded 2 different versions of formik?

**Comment by puru0019** [comment]
> @puru0019 were you able to determine whether you had loaded 2 different versions of formik?

Yes. Thank you for the information
