### ISSUE TITLE
Cannot call an event handler while rendering

### ISSUE THREAD

**Issue by FredyC** [jaredpalmer/formik#1678]
### Current Behavior

Calling API too soon will yield error `Cannot call an event handler while rendering` despite using `React.useEffect`.

```js
  React.useEffect(() => {
    formik.setFieldValue('data', [1, 2, 3])
  }, [])
```

It is originating from that shiny `useEventCallback`...

https://github.com/jaredpalmer/formik/blob/921ec8dab84d62d0d1fdb92780a333ad011734c5/src/Formik.tsx#L984

It's all coming from the fact that React evaluates effects calls a bottom to top which is quite problematic in this case.

### Expected behavior

In some not-so-rare cases, it's necessary to set form _initial values_, but because of some other complexities, reusability principles and weather condition (obviously), it's not possible to do it at a form level.

The current workaround is to wrap that API call to `setImmediate`, but that's hardly a DX friendly.

### Reproducible example

https://codesandbox.io/s/frosty-poitras-fme81

### Suggested solution(s)

I am trying to understand why that hook was used in a first place. Reading relevant PR https://github.com/jaredpalmer/formik/pull/1566 and still don't get it. Some class-related shenanigans 😵 

@VanTanev has actually suggested alternative implementation https://github.com/jaredpalmer/formik/pull/1566#issuecomment-497933241 which at least does not throw an error. Not sure why it was dismissed without any comment.

**Comment by clementoriol** [comment]
I'm experiencing this too since I've upgraded formik to `2.0.1-rc.8`, but I'm having a lot of issues to pinpoint exactly where and how it's happening.

It's currently making my e2e (using [Cypress](https://www.cypress.io/) tests fail randomly in CI (they fail on application errors). I can't seem to get a decent stacktrace so it's hard to reproduce on my end, and I've never seen this error when manually browsing through the app. 
Could this be somehow triggered by how fast Cypress is?

I realise that's a pretty vague way to describe the issue, but currently that's all I got! I'll try to investigate some more, hoping I'll get a sense of where it's coming from.

**Comment by jaredpalmer** [comment]
Releasing rc.13 now

**Comment by FredyC** [comment]
Feel free to close if you are satisfied with the solution. We are not using Formik anymore 🙊 It has nothing to do with the speed of development, but because the internal pattern seems kinda wrong and causing numerous issues and deoptimizations which we are unwilling to accept for our products.

I've polished the initial idea [from my article](https://levelup.gitconnected.com/formik-with-react-hooks-and-mobx-1493b5fd607e) and wrote fully MobX powered lib with similar API to Formik. Works beautifully with half the effort to make a coherent experience. It's not public (yet) though.

**Comment by sibelius** [comment]
rc.13 is working fine for us

tks
