### ISSUE TITLE
Cleanup Github Issues?

### ISSUE THREAD

**Issue by derek-adair** [jaredpalmer/formik#1781]
## ❓Question
Can we get some cleanup in the issues? 

it's very hard to navigate the 280+ open issues

**Comment by derek-adair** [comment]
This would make contributing easier and a more accurate picture of the health of this project.  The first thing i think when I see any project like this is...

"Oh boy, another inactively maintained project!!"

**Comment by johnrom** [comment]
@derek-adair you are free to chime in on issues, resolve other folks' issues via comments, and draw attention to any issues which can be closed due to said resolution or to being duplicates of other issues (there are a ton!), open PRs from a personal fork, and ask for review in order to merge and close issues. I think many maintainers work here either in their free time or when there is flexibility with their work schedule.

Many issues that exist here depend on Formik v2 branch to be merged, which is a huge overhaul of the project. So once that drops, maintainers will likely be able to go back to a significant percentage of issues and confirm whether they are resolved by v2.

I definitely understand that 280 open issues is crazy, but if you look at a project like [React itself](https://github.com/facebook/react/issues), open issues are a side effect of being a popular open source community. The frequency that issues are opened here is staggering, and resolving peoples' issues is most of what I do here since I don't really have time to jump into the code.

Now what would it take to get this issue closed? :)

**Comment by derek-adair** [comment]
Thanks that is enough for me i appreciate your time and will do what i can to help
