### ISSUE TITLE
How to reset form without clearing fields?

### ISSUE THREAD

**Issue by hopewise** [jaredpalmer/formik#1789]
## ❓Question

After I call `validateForm`, when field loses focus, it got validated, although I have `validateOnBlur={false}`

I've noticed that `validateOnBlur={false}` works as expected before calling `validateForm`, but it will work as if it has been set to true, after I call `validateForm`

My work around was to reset the form by calling `handleReset`, that has made `validateOnBlur={false}` to work properly, but reseting the form will clear the fields also.

How can I always make `validateOnBlur` to false, even after calling `validateForm` ?

**Comment by johnrom** [comment]
@hopewise do you have a sandbox or can you fill out the table from the "Bug Report" issue template? It's hard to tell exactly what's happening here without a specific example -- it should work as you described.

Looking briefly at the code it looks like validateOnBlur is always checked before validateForm is executed on both v1 and v2, but validateOnChange would also need to be false to prevent a field from being validated when it is changed. If you're using a `FastField` I believe it would actually be validated when it is blurred because FastField updates the field value when it is blurred for performance.

**Comment by hopewise** [comment]
Thanks @johnrom , my bad, I had `onBlur={handleBlur(validation_name)}` in the field template which I missed to note.
