### ISSUE TITLE
FieldArray in Modals

### ISSUE THREAD

**Issue by mbrahimi617** [jaredpalmer/formik#1815]
I saw a previous issue in which you guys alluded to the fact that nested forms is invalid, or at the very least improper. You see I have a form in which one of the fields is a field array that is mapped as rows of a Material UI Table. I'd like to have modals for creating, updating, and deleting rows which of course can be achieved by passing `arrayHelpers` to the modal components.

I saw a video in which Jared, just as is seen in the docs, uses a FieldArray to create a form inspired by a Slack invite. However, the issue is that he does all of his CRUD operations on the same component and he has to add an empty item before it can be edited or deleted.

Which brings me to my issue, my CRUD operations are going to happen in separate modals for which I'd like to manage the fields with Formik rather than state. Furthermore, this will ensure that the data is not empty before editing and deleting. My question is how do I achieve this without bad practices. It seems like FieldArray was designed with good intention but it may need a few tweaks to ensure that empty data must be added before it can be indexed and managed with `arrayHelpers`

**Comment by johnrom** [comment]
In v2, a nested form can _override_ the context of a form that it is within due to the way React Context works. I'd need a codesandbox reproduction to really comment on the issue you're having here. Can you attempt to minimally reproduce your example issue using one of the following templates?:

Formik v1: https://codesandbox.io/s/zKrK5YLDZ
Formik v2 RC: https://codesandbox.io/s/9w3zyjlqo

**Comment by mbrahimi617** [comment]
Well I suppose I could try to draw one up when I have the time, but I really should be getting ahead with my project without Formik unfortunately. Anyways, the primary issue is that in order to be used items in an FieldArray must be indexed. This implies that if we were to have a modal to add to the array, we can't access or validate the fields in the modal via Formik because it has yet to exist in the list and thus has no index. 

We'd literally have to push an empty object to the list and only then will we be able to use it in the create modal. Obviously, this isn't the intended behavior because I don't want an empty row in my table at any time during execution. Rather it would be nice if Formik had a concept of a temporary instance per FieldArray instead of needing an index. By the way, I'm using Material UI if that wasn't clear.

**Comment by mbrahimi617** [comment]
When is Formik 2 going to be available? I'm only seeing 1.5.8 in the docs.

**Comment by mbrahimi617** [comment]
Here's the example John: https://codesandbox.io/s/unruffled-babbage-1wu4h?fontsize=14

**Comment by johnrom** [comment]
@mbrahimi617  I see the issue you are running into here. For the purposes of Formik state management, I'd try to think of the new item the same way as if you had added it inline in the table. You couldn't render a new line in the table unless there was a dummy object you could start editing. All of formik's edits have to apply in place to it's state, so to add "J" to the first name of a new user, your object would have to look like this:

```
{
        people: [
          { name: "Sam", age: 20 },
          { name: "Bob", age: 45 },
          { name: "Jen", age: 23 },
          { name: "J", age: 0 }
        ]
      }
```

On the other hand, if you think of them as two forms which you initially began thinking them of, it would make more sense that the `onSubmit` of the modal form would create a new element in the table form. This is only possible in v1 by manually hooking up all of your fields (AKA no using <Field />). Not too bad for a small create form like this, but if it's going to evolve a bunch it could be a pain. In v2 there would be no need to hook anything up manually except for what happens on Submit as the inner form will automatically bind its own context to any Formik Fields. 

Here's a v1 example: https://codesandbox.io/s/zen-greider-fx2um

The maintainers of this project haven't set a target date for Formik 2, but you're free to experiment with it and see if it does what you'd like it to. Unfortunately, if you're not comfortable with pre-release software for your project then you'll have to try again when V2 comes out, or manually hook up your inputs on the secondary field.

**Comment by mbrahimi617** [comment]
This looks nice but the primary problem is that it ignores the possibility of other fields aside from the array, where values is a new instance of the array rather than the entire form. I have other fields aside from the table but I wanted to abstract it to just the array portion in question.

**Comment by mbrahimi617** [comment]
This was my initial train of thinking but I wasn't sure how fields would work given the nested contexts of both Formik components, and I wasn't sure what the nested Formik component would return if not a form. Obviously that would be invalid HTML.

**Comment by mbrahimi617** [comment]
In the case of Formik 2 which context would `useFormikContent` refer to?

**Comment by johnrom** [comment]
> This was my initial train of thinking but I wasn't sure how fields would work given the nested contexts of both Formik components, and I wasn't sure what the nested Formik component would return if not a form. Obviously that would be invalid HTML.

It wouldn't be invalid html if the `modal` package you are using actually renders your Modal Content outside of the form (I assume it does as this is how most modals work). So you'll need a Form anyway in order to handle Enter for onSubmit or you'll have to tie the Form to the inputs manually with `form="myForm"`.

I don't really have time at the moment to demonstrate how v2 is done, but there are new docs right now being worked on here:

https://github.com/jaredpalmer/formik/blob/new-tutorial/docs/tutorial.md

We're reworking them to make them a bit simpler, but if you skip to the end you can see what the new API looks like and it's very similar to the old API except you can use things like `useField` and `useFormikContext` React Hooks to grab a reference to either a Field, or the props that would usually be grabbed from `<Formik>{(formikProps => {}}</Formik>` in any component inside of the hierarchy of `<Formik>`. Note that it'd _grab from the closest `<Formik>`_ so if you have nested forms, it'd grab the context of the closest one -- within the Modal it would grab the Modal Formik props.
