### ISSUE TITLE
React Suspense when submit?

### ISSUE THREAD

**Issue by javierguzman** [jaredpalmer/formik#1839]
Hello for the very first time around here,

I have a functional component wrapped by Suspense. Such a component renders a login form(a Formik one!) . When I submit, I send the request to the backend, etc. and I throw the promise in order to trigger Suspense.
```
            onSubmit = { (values, { setSubmitting }) => {
                    setSubmitting(false);
                    throw props.loginLocalUser(values, t);                                        
                }
            }
```
However that promise is not caught by anybody. How would be the best approach to achieve what I want? Presumably the Suspense mechanism works only if you throw the promise inside the function body.

Thank you in advance!

**Comment by ReasonX7** [comment]
IMHO, your question is not very relevant to `Formik`. It's more about how JS engine implements async operations.

I also, don't understand why are you making `setSubmitting(false)`?

The promise won't be caught by React, since the `try/catch` block was already executed, as soon, as the component was rendered. It is similar, as if you would try to do something like this:
```js
try {
  setTimeout(() => throw something);
} catch (ex) {
  // This block will never be executed.
}
```
From my experience, using `Suspense` to display every async operation in your component is not the best idea. You can end up with `Suspense` wrapper hell, when you need to remember every component that throws promises, which can be pretty unobvious.

[Here](https://codesandbox.io/embed/musing-shape-1jlwz?fontsize=14) is an example of how you can do it with `Suspense`, but it is very dirty and ugly solution.

**Comment by javierguzman** [comment]
Hello ReasonX7!

Thank you very much for your help. Yes, I guess it is not fully linked to Formik, but I was just wondering if there was by any "hack" from Formik in order to be able to use Suspense as I have seen Jared in some videos explaining Suspense. I think I will follow your advise and not use Suspense for everything. 

Before I close; What do you mean by why I am calling setSubmitting(false)? In some examples from the website it does that. Is not needed?:S

Again thanks! 

Regards

**Comment by fmoliveira** [comment]
@javierguzman It's actually fine to call `setSubmitting(false)` according to the documentation at https://jaredpalmer.com/formik/docs/guides/form-submission#submission.

That is just not the usual order to call it. One would generally want to call it **after** the submission is finished, not as the first thing in your `onSubmit` handler. This is not something enforced, though, but it is a best practice. Please refer to the link above for details.

I suggest you post your original question to Stack Overflow to get more views and hopefully get the help you need.

**Comment by javierguzman** [comment]
Thanks for the response Felipe!

That makes sense. I placed it at the very beginning because I had throw it was not gonna to be executed what is after I believe.

I will close this then.
