### ISSUE TITLE
Allow default import of Formik

### ISSUE THREAD

**Issue by MaffooBristol** [jaredpalmer/formik#1849]
### Current Behaviour

You need to include Formik like so:
```js
import { Formik } from 'formik';
```

But I naturally do this:
```js
import Formik from 'formik';
```

This creates the React error message of:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Okay, React does kinda tell you that you've probably buggered it up but it doesn't say which bit is wrong.

### Desired Behaviour

Just allow a default import, seeing as I never use anything other than `Formik` itself anyway. Or people could do what they do in React and do `import Formik, { foo } from 'formik';`

### Suggested Solution

Add an export default

### Who does this impact? Who is this for?

It's a couple of minutes of "huh why is that erroring when it worked in another component?" head-scratching on a sleepy Monday morning that I'd rather not have. It's obviously low urgency.

### Describe alternatives you've considered

Just try and not be a moron and remember how to include a library.

**Comment by StJohn3D** [comment]
I'm getting the same error despite importing the correct way.
`import { Formik } from 'formik';`

**Comment by johnrom** [comment]
@MaffooBristol default exports are a pretty controversial topic, but I personally avoid them because they create the ability to incorrectly name variables. For example, you could write `import React from 'formik';` and spend forever figuring out why React doesn't have a `memo` function.

From a maintenance perspective, in the future we might decide that v7 of Formik uses a new "NewFormik" container, and at that point we wouldn't be able to change the default export to use it due to backwards compatibility. At that point, the default would be the legacy component, and we'd get issue after issue about it. Plus, some people use `withFormik`, so they might say "instead you should export `withFormik` as default!"

Now, it's your choice whether or not you prefer default exports, but I would guess the maintainers have made this decision explicitly. I might recommend trying out TypeScript because it would scream at you as soon as you tried to `import Formik`, and say something nice like "Did you mean { Formik }"?

In my opinion, I'd rather not export a default, but other maintainers may disagree.

**Comment by jaredpalmer** [comment]
This goes against my coding guidelines. Default exports are not tolerated unless forced by framework-specifics (such as react.lazy or a next.js page).
