### ISSUE TITLE
Subscribe to FormikMessage dispatches

### ISSUE THREAD

**Issue by IanLondon** [jaredpalmer/formik#1854]
## 🚀 Feature request

It would be cool to allow users to "subscribe" to v2's internal `useReducer` dispatch. My use case is that I want to implement analytics on a Formik form around events like onBlur. I have a handful of different form components (using `Field`), so without a subscription to the central message flow, I have to do `onBlur={e => {doOnBlurSideEffect(e); form.onBlur(e)}}` on all the components. But since Formik is acting as the central place for these messages, it would be nicer to do this there.

### Current Behavior

Can't do it?

### Desired Behavior

Add a prop to `FormikProps` that allows me to attach a subscriber/listener function for side effects. This prop would take a function that takes the `FormikMessage` action as its argument.. Maybe `listener`?

### Who does this impact? Who is this for?

Formik users who want to side-effect in response to Formik events, probably for analytics

### Describe alternatives you've considered

- Handling it on a per-component basis (perform my onBlur side-effect in every place I call `field.onBlur`)
- Infer changes afterwards by comparing previous Formik render props to current ones after each render, eg `if (prevTouched[name] !== touched[name]) { doOnBlurSideEffect(name) }` but this is super hacky and brittle

**Comment by dommuldoon** [comment]
Can i ask what is in your doOnBlurSideEffect()? ie are you able to set a condition to do stuff only if field is invalid onBlur? We are having trouble with this as fields always seem to go invalid for us for a split second and not viewable in browser - #1863

**Comment by IanLondon** [comment]
@dommuldoon I did notice that problem where fields go invalid, if I remember right it they were treated for one render cycle as being empty (or maybe a previous value) onBlur even though they're not, then immediately after it rerenders with the correct value.

To get around this "flicker" problem, I wound up memoizing the previous value of all fields (memoized previous values object gets updated onBlur) and only triggering the side effect onBlur the new value is different than previous. It's a hacky workaround.

(PS I'm using Formik v1, hoping there will be a better solution available in v2)

**Comment by jaredpalmer** [comment]
You can do this with just the DOM event and listen for actual blur events emitted by the inputs

**Comment by johnrom** [comment]
@jaredpalmer I think allowing a custom reducer to be passed in would allow users to decorate the reducer functionality without compromising how Formik works at all, closing all sorts of other "reacting to formik changes"-type issues that are abound here (auto-save, dependent changes, etc). I do understand it somewhat violates the "antithesis to redux-form" nature of Formik, but at the same time it doesn't roll back the real problem with redux-form which is that redux is global and there is no reason to store form data in redux _by default_. Allowing users to opt into this type of behavior will increase the use cases for Formik immediately. It would be as easy as exporting `formikReducer` and doing:

```
  const formikReducer = React.useReducer<
    React.Reducer<FormikState<Values>, FormikMessage<Values>>
  >(props.reducer ?? formikReducer, {
    values: props.initialValues,
    errors: props.initialErrors || emptyErrors,
    touched: props.initialTouched || emptyTouched,
    status: props.initialStatus,
    isSubmitting: false,
    isValidating: false,
    submitCount: 0,
  });
```

The user could then do something like: 

```tsx
const mySpecialReducer = (
  state: FormikState<Values> & MySpecialState, 
  msg: FormikMessage<Values> | MySpecialMessage
) => {
  formikReducer(state, msg);
  
  switch (msg) { 
    case 'MY_SPECIAL_MESSAGE': return { ...state, mySpecialProp: msg.payload }
  }
}

return <Formik overrideReducer={mySpecialReducer} />
```

Finally, I admit it's a can of worms we might not want to open, but we should maybe make it _hard to do_ but not _impossible_ for someone who needs this functionality. Keeping context in sync is a terrible way to manage things like autosaves and dependent fields because often time you need to use tons of refs and other things to make sure that everything is up to date, when the reducer does that for you.
