### ISSUE TITLE
'useFormikContext' is not exported from 'formik'.

### ISSUE THREAD

**Issue by vigneshwaran-chandrasekaran** [jaredpalmer/formik#1858]
### Current Behavior

https://github.com/jaredpalmer/formik/blob/master/examples/DebouncedAutoSave.js

const formik = useFormikContext();

./src/components/DebouncedAutoSave.js
Attempted import error: 'useFormikContext' is not exported from 'formik'.

**useFormikContext** not working

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | "^1.5.8"
| React            | "^16.9.0"

**Comment by vigneshwaran-chandrasekaran** [comment]
Version "^1.5.8" don't support this feature. sorry.

**Comment by Kielan** [comment]
I think this is accurate an accurate issue and shouldn't be closed without a readme update, this is not working and should be available....

**Comment by jaredpalmer** [comment]
This hook is not exported in 1.x. only in v2

**Comment by jaredpalmer** [comment]
This issue was opened when master branch reflected v2 while stable release was on v1

**Comment by jthornca** [comment]
I just updated my project to release 2.1.1 and it still isn't exported. I assume I have the right version because it also said that FormikActions wasn't exported, but at least the documentation mentioned that it was renamed to FormikHelpers.

![image](https://user-images.githubusercontent.com/48975873/72113307-e7c3cf80-32f4-11ea-9016-f1cc238f38dd.png)

![image](https://user-images.githubusercontent.com/48975873/72113356-0e820600-32f5-11ea-8c2a-51e2192be4d8.png)
