### ISSUE TITLE
[Question] Can I set initialValues in withFormik() ?

### ISSUE THREAD

**Issue by taneba** [jaredpalmer/formik#192]
I want to write something like this:

```
const formikEnhancer = withFormik({
  initialValues: props => ({ foo: 'something', bar: 'something' })
  enableReinitialize: true
})
```

Any idea to realize this?

**Comment by jaredpalmer** [comment]
Use mapPropsToValues

**Comment by taneba** [comment]
Thank you for the answer!
I'm sorry I missed enableReinitialize is available in withFormik API 😓

**Comment by mnieber** [comment]
@jaredpalmer  I also stumbled on this problem. AFAICT `mapPropsToValues` acts differently from `initialValues`, because - by default - the initial values are only evaluated once whereas `mapPropsToValues` is evaluated whenever the props change. 

I'd like the `initialValues` behaviour, and I'm using `withFormik`. Should that work? If `initialValues` doesn't work with `withFormik`, then could this be documented?

**Comment by sriram15690** [comment]
May I know if initialValues is supported for withFormik now in 2020?
