### ISSUE TITLE
Why is typeof initialValues just Values not Partial<Values> in TypeScript?

### ISSUE THREAD

**Issue by worudso** [jaredpalmer/formik#1928]
## ❓Question
I'm not sure it's intended or just missed.
If it is intended, I guess that the goal is forcing programmers to give any value to each field explicitly(while formik works well with unintialized values).
But I think it's hard to do sometimes.

Let's assume that you're writing a Formik form that sends a message to another user.

Its `Values` could look like
```tsx
interface Message {
  to: string // maybe an ID of an user
  body: string 
}

<Formik<Message> initialValues={{ to: "", body: ""}}>
```

`to` in Message should inhabit a value when the form is submitted,
however, it can't be initialized with a value every time.
Imagine, there is a select box in the formik render component, and the select box will determine the value of `to`(the ID of message receiver).
Sometimes you can specify the receiver showing the form, but sometimes you don't.
But making `to` to `to?` or nullable is not the best option. Because it should not be null or undefined when it is submitted.

**Comment by branoholy** [comment]
I don't understand it either. I think it's intended because [the docs](https://jaredpalmer.com/formik/docs/api/formik#initialvalues-values) says:

> Even if your form is empty by default, you must initialize all fields with initial values otherwise React will throw an error saying that you have changed an input from uncontrolled to controlled.

But this is true only for native form elements. Custom components can handle their values before rendering and can transform `undefined` to an empty string (for example) if it's necessary. Also, custom components can be created without native form elements so this error won't be thrown even with `undefined`.

Is there another reason why `initialValues` are not `Partial`?

**Comment by johnrom** [comment]
Yes, because `touched` is not constructed unless a field is present in `values`.

#1967 #1850

**Comment by branoholy** [comment]
Thanks for info! It makes sense now. Hopefully, it will be improved in the future.
