### ISSUE TITLE
After submitting the form, the touched field is not a boolean if its value is an object

### ISSUE THREAD

**Issue by yarokon** [jaredpalmer/formik#1942]
### Current Behavior
<img width="1313" alt="Screenshot 2019-10-28 at 18 22 54" src="https://user-images.githubusercontent.com/4423716/67697492-4abdef80-f9b1-11e9-8881-55624719a529.png">

### Expected behavior

All fields should be set to true after form submission

### Reproducible example

```
    import ReactDateTime from 'react-datetime';
    import moment from 'moment';

    <Formik
      initialValues={{
        startDate: moment(),
      }}
    />

    <Field
      name={name}
    >
      {({ field }) => {
        return (
          <ReactDateTime
            {...field}
            dateFormat="YYYY-MM-DD"
            timeFormat="HH:mm"
            onChange={value => formik.setFieldValue(name, value)}
            onBlur={() => formik.setFieldTouched(name, true)}
            {...rest}
          />
        );
      }}
    </Field>
```

### Suggested solution(s)

fix setNestedObjectValues function 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.11.0
| Browser          | Google Chrome 77
| Yarn         | 1.17.3
| Operating System | macOS Catalina

**Comment by Fossan** [comment]
Hey guys, any update on that? Same happen with **Luxon's** `DateTime` for instance

**Comment by johnrom** [comment]
From what I can tell, there is absolutely no way for Formik to "set all fields as touched" with complex objects just by iterating through the initialValues object. In order to support this, we would need to base `touched` off of registered fields, which would be a completely breaking change. Personally, I think this would be a good change, as it would also provide a solution for the common questions: "why is initialValues required" and "why do I need to define initialValues for every field", but it would completely change Formik's API.

For now, the only way to work with this is to manually translate your object to a primitive (like `2019-11-29T15:45:54:0368` above) for storing in Formik's state. Related: #1525.

If you need to submit an object, you'll have to translate it back during `onSubmit`.

**Comment by Pawelh133** [comment]
I tested it on Date objects and I agree with @johnrom  - you heave to keep simple value instead of object like moment or js Date. Then touched works fine. (I tested on Formik v2.1.4).  You can also keep it as unix value (number) instead of string. Its easy to deal with momentjs.

**Comment by yarokon** [comment]
I agree with you @johnrom. When I tried to implement this on my own, I realized that it was impossible to do. On the other hand, it's not possible to keep all values as primitives, especially for third-party libraries. Also if this field uses a validation, it is inefficient to convert a primitive value to the moment object each time. I prefer not to convert primitive values ​​back and forth and try to do not to pay attention to how the “touched” object looks.
