### ISSUE TITLE
Validation not working in Firefox

### ISSUE THREAD

**Issue by carolinmaisenbacher** [jaredpalmer/formik#1997]
### Current Behavior
When running a formik form, with a Yup validationSchema in a Firefox browser, form errors are not recognized.

To reproduce the error, I used the basic formix sandbox example and tested it with lambdatest, which sets up a whole vm, to make sure this error has nothing to do with my machine.

The only thing I switched was upgrading formik v.2.0.3.

First I tested with 
Chrome 77, on Windows 10. Here everything works as expected.
<img width="1680" alt="Screenshot 2019-11-06 10 24 26" src="https://user-images.githubusercontent.com/32734844/68263004-ddc8ea80-007f-11ea-902f-8df6c2273eff.png">

However, in Firefox, here I used 69, on Windows 10, the error is not displayed, nor does it appear in the form state.
<img width="1680" alt="Screenshot 2019-11-06 10 25 42" src="https://user-images.githubusercontent.com/32734844/68263005-de618100-007f-11ea-9a83-b6c660199249.png">

Both times I typed in an invalid email and unfocused the field afterwards.

### Expected behavior

I expected to see the email error message in the forms state.

### Reproducible example

Use the basic formik codebox example and run it in a firefox example. Try to type an invalid email.
https://codesandbox.io/s/formik-example-22biw

### Additional context
I myself am running on MacOs Mojave and the Firefox Developer Edition and I stumbled upon this problem using formik for a larger application. There formik does not only not validate, but the whole application crashed, when a validation error occurs.

I also tested it with the original sandbox example which uses v1.5.8 and the same error occurs.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3
| React            | 16.8.6
| Browser          |  Firefox 69
| Operating System | Windows

**Comment by VincentvD** [comment]
I encountered this as well after upgrading to 2.0.3. For now I have reverted to 1.5.8.

**Comment by dbanisimov** [comment]
Works for me with Formik 2.0.4, Firefox 70, Win 10, React 16.12.0, bundle made with create-react-app 3.1.1.

While digging around the issue I've found that the validation silently fails on 1.5.7, but shows a warning on 2.0.4: `An unhandled error was caught during validation in <Formik validationSchema />`. The difference is likely caused by this change #1575 that introduced the warning.

When I stopped in the debugger on `runValidationSchema` function I've found that the error received by Formik is not a `ValidationError` as expected, but a different one with a message "Unexpected frame by generating stack." that wraps the original ValidationError. That's why Formik doesn't read the errors from the Yup validation.

This looks like an issue with a codesandbox environment, as I don't see it when set up locally. This issue on CodeSandbox looks related: codesandbox/codesandbox-client#1744. For folks above I'd recommend to try to build it locally, or with a different bundler/polyfill, and if those don't help take a look at the above-mentioned functions in the debugger.

**Comment by VincentvD** [comment]
I was planning on creating a small example (outside of codesandbox) to test this. But I first checked my previous sandbox example with all updated deps and I cannot reproduce this issue.

**Comment by carolinmaisenbacher** [comment]
I came across the issue again. 
This time I realised, the validation only fails, when the developer tools are opened while editing a form in Firefox Developer Edition.

That makes the bug in my opinion irrelevant and I would suggest to close this issue.

**Comment by rvanlaarhoven** [comment]
In my case, when using an input with e.g. type `email`, the browser blocks the actual form submit because of its' own validation checks and so does not mark the fields as touched. This way the error message is not shown when you enter a non-email value in the email field and hit submit.

**Comment by jaredpalmer** [comment]
<img width="425" alt="Screen Shot 2020-02-26 at 10 09 54 AM" src="https://user-images.githubusercontent.com/4060187/75357938-24855f00-5880-11ea-9e96-858986cf584b.png">


Just tested in 2.1.4. Works as expected.

Hitting enter to submit while in an input will not trigger a blur event if there is a browser input validation error in FF. This can be seen in screenshot with `<input type="email" />`.

**Comment by jaredpalmer** [comment]
https://codesandbox.io/s/formik-example-8jll6
