### ISSUE TITLE
setFieldValue in FormikContext has wrong signature

### ISSUE THREAD

**Issue by spawluk** [jaredpalmer/formik#2065]
### Current Behavior

I use custom component connected to `FormikContext` (ex. `UserFullName`). It is imposible to use generic hook `useFormikContext<T>` with nested objects. Helper functions has signatures that allow only first level properties set (ex. `setFieldValue`).

### Expected behavior

Being able to use `FormikContext<T>` helpers functions with nested fields without TypeScript errors.

### Reproducible example

https://codesandbox.io/s/formik-206-setfieldvalue-signature-qrezs

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.6
| React            | 16.8.4
| TypeScript       | 3.7.2
| Browser          | any
| npm/Yarn         | 6.11.3
| Operating System | Windows 10

**Comment by ldicocco** [comment]
This one is a very strange regression bug. The root cause is that https://github.com/jaredpalmer/formik/blob/master/src/types.tsx#L90 and the other similar type definition don't do what was the intention to do.
As string literal types are subtypes of the type ```string```, ```keyof Values & string``` is equivalent to just ```keyof Values ```, as ```keyof Values | string``` is equivalent to just ```string```.
Unfortunately this means that for TS users not just nested fields cannot be used without a cast to ```any```, but even common idioms like ```form.setFieldValue(field.name)```, required with many components library with a non standard onChange, require a cast to any, that in many development environments may even be forbidden.
The funny thing is that this mistake is not new. It's in the code base since more than 1 year. This can be seen in version 1.5.8 https://github.com/jaredpalmer/formik/blob/v1.5.8/src/types.tsx#L86 , where the code is the same.
But it had no effect as in https://github.com/jaredpalmer/formik/blob/v1.5.8/src/types.tsx#L119, for mysterious reasons, the same type was overridden with the right one.
Unfortunately the same override is not possible, AFAK, with types in external libraries used as part of type alias, as it happens in v2.
I'm thinking about submitting a PR with the trivial fix.

**Comment by ldicocco** [comment]
Unfortunately at the moment tests are failing in master, so a PR with the simple fix is not possible.

**Comment by ldicocco** [comment]
I've submitted a PR with a fix: https://github.com/jaredpalmer/formik/pull/2079.
