### ISSUE TITLE
CDN link / generation is broken

### ISSUE THREAD

**Issue by daniel-stoneuk** [jaredpalmer/formik#2108]
## 📖 Documentation

Hi, unfortunately the CDN link on this page does not work, and when using the minified version I get the following console error message on page load

Uncaught TypeError: s is not a function
    at x (connect.tsx:40)
    at FieldArray.tsx:350
    at formik.umd.production.min.js:1
    at formik.umd.production.min.js:1

https://jaredpalmer.com/formik/docs/overview#cdn

Please can this be investigated since the latest version of formik that I can use is 1.5.8 because of this. Thank you!

**Comment by amarjayr** [comment]
@jaredpalmer I do not think this issue is resolved, I am getting this exact issue as well and see a reference to  it here: ### https://github.com/jaredpalmer/formik/issues/1463#issuecomment-624564924 

This happens with both URLs:
https://unpkg.com/formik/dist/formik.umd.production.min.js
https://unpkg.com/formik/dist/formik.umd.production.js

connect.tsx:40 Uncaught TypeError: s is not a function
    at x (connect.tsx:40)
    at FieldArray.tsx:374
    at formik.umd.production.min.js:1
    at formik.umd.production.min.js:1

**Comment by benjaminsuch** [comment]
Can confirm. To reproduce you just need to add React from CDN and Formik.

**Comment by lucipak** [comment]
Why is this closed? This is still happening.
