### ISSUE TITLE
How to avoid the console.warn: ...but you forgot to pass an `id` or `name`

### ISSUE THREAD

**Issue by dennisat** [jaredpalmer/formik#2173]
## ❓Question

Having `<input>` elements without `id` or `name` attrs, the Formik is complaining that `id` or `name` are required. 

Some components in the form might have multiple internal `<input>` elements that are not considered as part of the form but only helpers of some components.

For instance, imagine a Map component with a search bar. The value of the search bar `<input>` is not part of the form, but Formik consoles warning that `id` or `name` are required.

What's the best practice to avoid this console.warns?

**Comment by jaredpalmer** [comment]
You’re or the component somehow passing handleChange to these inputs which don’t provide the underlying event. When this happens, I would suggest manually using setFieldValue or the new setValue helper (returned from useField) to set the value of the input instead of relying on the handleChange. See the docs on React Native (since it is the same approach).

**Comment by dennisat** [comment]
I can handle and save value properly. **This is not a problem.** I use the `setFieldValue`.

First of all, I am using the `useFormik()`.

Because in the `<form>` there is a helper `<input>` that is not part of the form in real, formik receives `change` events from this `<input>` and it complains "you forgot to pass an `id` or `name`".

But this is not forgotten, it is just a helper `<input>` and is not part of the form and we don't want to save any value from it.

The problem **is not how to update** the field value, but how to **avoid** this console.warn.

I hope this explanation makes cleaner the problem.
