### ISSUE TITLE
Interesting enableReinitialize and autosave interactions

### ISSUE THREAD

**Issue by dbousamra** [jaredpalmer/formik#2470]
## ❓Question

I have a Formik setup where I have a form with an autosave component against a server with some dynamic rules engine type behaviour. I.e. if I modify field A, it's possible it can also change field B. When the form saves, the server sends back a full copy of the `initialValues` and with `enableReinitialize`, and the form is updated. I debounce my autosave requests to every 1000ms. 

An issue arises when a form field is changed during an autosave HTTP request to the server.

Here's a rough timeline to illustrate the issue:

1. 12:00:00:000: Type `'HELLO'` in field A
2. 12:00:01:000: Debounced autosave request is made (takes 500ms to complete)
3. 12:00:01:001: Type `' WORLD'` in field A
4. 12:00:01:500: Responses comes back from server with the saved data.

The `' WORLD'` that was typed in field A is overwritten with the servers response, as the `initialValues` have changed. This is really frustrating to the user when it occurs.

**What do you suggest for a situation like this? I want to capture the changeset that occurred while the request was taking place.**

Edit: Is this something that could be enabled by https://github.com/jaredpalmer/formik/issues/2428 ? Is there a workaround I can take immediately?

**Comment by johnrom** [comment]
it's not necessarily tied to #2428, though that would provide a workaround. I'd recommend not updating initialValues directly from the autosave request. autosave isn't generally a two-way data stream. think about it, especially because you're already debouncing these are by design not identical sets of data. it appears to me that the user's input is going to have unintended circumstances by altering their previous input.

It's hard for me to envision a valid use case, but even if your use case is perfectly valid, I'd make sure the form is still in the right state to begin with before updating initialValues. After all, what if the changes the user has currently entered would result in a different change than the change the autosave was triggering?

```
const debounceInterval = 250; // or whatever

const MyAutoSaveWithEffects = props => {
  const [initialValues, setInitialValues] = React.useState(props.initialValues);
  const currentValues = React.useRef(initialValues);
  const debouncedAutoSaveAndUpdateInitialValues = React.useCallback(debounce(async (valuesToSave) => {
    const returnedValues = await props.doAutosave(valuesToSave);

    if (areEqual(currentValues.current, valuesToSave)) {
      setInitialValues(returnedValues);
    }
  }, debounceInterval), []);
  const autoSave = React.useCallback(async (valuesToSave) => {
    currentValues.current = valuesToSave;

    debouncedAutoSaveAndUpdateInitialValues(valuesToSave);
  }, [debouncedAutoSaveAndUpdateInitialValues]);

  return <Formik initialValues={initialValues}>
    <AutoSavingComponent onSave={autoSave} />
  <Formik>;
}
```

**Comment by dbousamra** [comment]
This is a really good idea, thank you.

I'll give it a shot and see how it behaves.

**Comment by johnrom** [comment]
I would just create a component with a useEffect on formik.values. Like this, but with hooks: https://gist.github.com/jaredpalmer/56e10cabe839747b84b81410839829be

**Comment by dbousamra** [comment]
@johnrom Sorry, would it be possible to get a more complete MVP of the approach. I spent the entire day trying to get something working, but I kept running into issues.

**Comment by johnrom** [comment]
If you post what you've tried on Codesandbox I can take a look and see if I can tell what's going wrong.

**Comment by dbousamra** [comment]
https://codesandbox.io/s/formik-autosave-duplicates-gup2h?file=/autosave.js

It's pretty hacked together, but this more or less does what I need it to:

- Saves are debounced
- The form fields are updated from the server, but never overwritten unless they are 100% up to date.
- Optimistic locking via the version field.

Do you have any feedback? I feel I am doing some weird stuff in the else clause here:

```
if (_.isEqual(currentValues.current, valuesToSave)) {
  setInitialValues(returnedValues);
} else {
  const newValues = {
    email: currentValues.current.email,
    version: returnedValues.version
  };
  setInitialValues(newValues);
  await doWork({
    valuesToSave: newValues,
    setSubmitting,
    isSubmitting: false,
    dirty: true
  });
}
```

I call doWork again, because dirty doesn't seem to be being set to true when I set the initialValues

**Comment by johnrom** [comment]
I don't think dirty matters, since we just want to make sure the value is not the same as the last autosave. If it were to be different than the last autosave, but the same as the original initialValues, we probably want to use the autoSave result anyway, since it technically would not be in sync with the server anymore. I changed AutoSavingComponent to only fire when not submitting (once submitting is finished, it would be _not submitting_ and autosave would fire), and inverted the control to the Form instead of within the autosaving component because it doesn't need to know anything about the callback itself.

https://codesandbox.io/s/formik-autosave-duplicates-s0svu?file=/index.js

**Comment by johnrom** [comment]
I made some more changes to tidy up situations where the user kept editing during onSave.

**Comment by dbousamra** [comment]
Thanks @johnrom, appreciate your help with this.

Your changes are very interesting, but I notice you remove the optimistic concurency lock I had in there. If an submit is sent with a version, and the DB doesn't have that version, I need to throw an error, as the client is acting on stale information. 

How do I handle that in your code? I tried adding back in the setting of the initial values to increment the version but it doesnt work

**Comment by johnrom** [comment]
It looks like it's working to me. Instead, I'd assign a Nonce or GUID to a user when they load the form. If that matches, it should always accept the latest user input as the final value of the autosave -- no need to version it. If it does not match, that means someone else tried to autosave and the client is acting on stale data. WordPress tackles it kind of like that, with the added bonus that a second editor will get a message like "X is currently editing this page. Take Over? Or go back?" -- taking over will then prevent X's autosaves from working.

**Comment by dbousamra** [comment]
@johnrom Thank you so much for your help. That suggestion was great. I've redesigned our editor to work similarly to wordpress.
