### ISSUE TITLE
Confusing props

### ISSUE THREAD

**Issue by pavel-sindelka** [jaredpalmer/formik#2508]
What is the difference between FastField component's props `as` and `component` and why `children` render function params don't contain custom props like `as` and `component` do?

**Comment by hrgui** [comment]
### `as` 
https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Field.tsx#L222
- spreads `field` (value, onBlur, onChange) and spreads custom props:

### `component`
https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Field.tsx#L192-L208
- `field, form` will be sent as props (not spread)
- spreads custom props

### `children`
https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Field.tsx#L171-L190
- `field, form, meta` will be sent as props
- custom props are not sent over, because we can use custom props normally through regular variable scope:

```jsx
const MyCustomField = ({ name, myCustomProp }) => {
  return (
    <FastField name={name}>
      {({ field }) => {
        return (
          <div>
            {myCustomProp} {/* note that myCustomProp can be used here */} 
            <input {...field} />
          </div>
        );
      }}
    </FastField>
  );
};
```

**Comment by pavel-sindelka** [comment]
@hrgui Thanks a lot!

I have last one question about FastField... Is it possible to rerender FastField component on change some custom prop? Because I tried it and nothing happened... until I change field value the custom prop wouldnt pass down.

**Comment by hrgui** [comment]
@pavel-sindelka , yes it is possible. There is a shouldUpdate prop that is passed in prevProps and currentProps. It runs on shouldComponentUpdate.

**Comment by pavel-sindelka** [comment]
@hrgui great! 👍  so I have to implement shouldComponentUpdate on my own like this:

prevProps.name !== props.name ||
getIn(prevFormik.values, prevProps.name) !== getIn(formik.values, props.name) ||
getIn(prevFormik.errors, prevProps.name) !== getIn(formik.errors, props.name) ||
getIn(prevFormik.touched, prevProps.name) !== getIn(formik.touched, props.name) ||
prevFormik.isSubmitting !== formik.isSubmitting ||
Object.keys(prevProps).length !== Object.keys(props).length ||
!shallowEqualObjects(prevProps, props)
