### ISSUE TITLE
Formik key error using FieldArray component

### ISSUE THREAD

**Issue by vinkovsky** [jaredpalmer/formik#3393]
### Current Behavior

I am using select component in formik to display multiples fields, but there is a key error.

### Expected behavior

No key errors

### Reproducible example

My code snippet: https://codesandbox.io/s/loving-shirley-r0jlh?file=/src/income-info.jsx

Steps to reproduce:

1. Try to select some value and click "add" button
2. Select some value in the next one
3. Click the "remove" button in the first item and change select value in the remaining item
4. At this step you can see the new item added (this is unexpected behavior) and errors in the console

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.2.0
| React            | 16.5.0
| Browser          | google chrome
| npm/Yarn         | npm
| Operating System | windows 10

**Comment by diegocasmo** [comment]
This is happening because of how the `FieldArray` items `ids` are being managed, which might create duplicates on the `replace` action due to it referencing wrong indexes.

> 1. Try to select some value and click "add" button

This will create two items, one at index `0` and another one at index `1`

> 2. Select some value in the next one

This will change the value of the item at index `1`

> 3. Click the "remove" button in the first item and change select value in the remaining item

This will remove the item at index `0` (so there's only one item with `id=1` in the array), and replace the item at index `1`, but since there's no item there (the array has length 1), it will create a new one at that index (this is the problem). 

I've updated your code snippet here, hopefully this helps 🙂: https://codesandbox.io/s/formik-3393-fixed-x5ofy?file=/src/income-info.jsx.
