### ISSUE TITLE
handleChangeValue on Array

### ISSUE THREAD

**Issue by bzuker** [jaredpalmer/formik#40]
First of all, great work!

After seeing issue #11 I tried to accomplish what  @eonwhite suggested, as in creating a Component that would receive all the values from an array and the `handleChangeValue` function.

I couldn't find a way to update just a particular instance of the array, but instead I had to 'recreate' the entire `emails` array with the changed value.

Is this the way I'm supposed to be using `handleChangeValue` or is it something I'm missing?

```javascript
const Emails = ({ handleChangeValue, emails }) =>
  <div>
  {
    emails.map((m, i) => 
      <input 
        name={`email${i}`} 
        value={m} 
        onChange={(e) => {
          const { name, value } = e.currentTarget;
          let newEmails = [...emails];
          newEmails[i] = value;
          handleChangeValue('emails', newEmails)} 
        }
        />)
  }
  </div>
```

The entire [sandbox](https://codesandbox.io/s/Nx0J9rZ3z)

Thanks!

**Comment by jaredpalmer** [comment]
This works, although I suggest using a class component instead of a render callback for performance reasons. 

If you need per-`email` input validation/error messages, you will need to use the method I described in #11 wherein you flatten the array to unique keys:

https://github.com/jaredpalmer/formik/issues/11#issuecomment-312449018
