### ISSUE TITLE
react-native is a required dependency?

### ISSUE THREAD

**Issue by Guymestef** [jaredpalmer/formik#421]
My project is using typescript, I upgraded formik from 0.11.0-rc.2 to 0.11.9, and now my webpack build is outputtingthe error:
    ERROR in [at-loader] ./node_modules/formik/dist/formik.d.ts:4:39
        TS2307: Cannot find module 'react-native'.

## Current Behavior
react-native is a required dependency

## Desired Behavior
react-native is not a required dependency

## Info
 - Formik Version: 0.11.9
- OS: windows 10
- Node Version: 9.5.0
- Package Manager and version: npm 5.6.0
- Typescript: 2.7.1

**Comment by corydeppen** [comment]
One workaround, similar to what's needed for the [missing prop-types declaration](https://github.com/jaredpalmer/formik/issues/316), is to install `@types/react-native`. Unfortunately, this causes the build to throw an error `Duplicate identifier 'require'` as mentioned in DefinitelyTyped/DefinitelyTyped#16825.

@jaredpalmer Since this is slightly different than the prop-types issue, do you think `@types/react-native` should be added to `dependencies` so TS devs don't have to worry about the extra install step? Or should this extra dependency be included with `@types/prop-types` in the install instructions?

**Comment by corydeppen** [comment]
It looks like the `Duplicate identifier 'require'` error may have been hit and caused the `@types/node` dependency to be removed and a [small workaround](https://github.com/jaredpalmer/formik/pull/379/commits/b68c64aa795caa287758e1e84a72deab8b13860d#diff-34219b6b803d5570dffa8d0b3695a6b7R13) to be added to Formik. I'm hoping this isn't the recommended solution for devs relying on the Node types.

**Comment by jaredpalmer** [comment]
Yeah we are going to need to drop react-native TypeScript support. I tried and thought I had it working and tested on like 5 projects of mine. However, clearly I broke the universe. I’m out at dinner, but the revert is as follows: remove `types` array from ts config, uninstall/remove react-native types, remove that declaration, reinstall @types/node. 

If someone can submit a PR I can merge ASAP and release off my phone’s
