### ISSUE TITLE
When is it worth waiting for a stable version?

### ISSUE THREAD

**Issue by andrew-polyansky** [jaredpalmer/formik#435]
## Question
You made a awesome form. 
I'm looking forward to a stable version like v1.0.0.
Could you please provide more info about it, when is it to be expected?   :relaxed: :rocket:

**Comment by jaredpalmer** [comment]
@andrew-polyansky thanks for the kinds words. I have been hesitant to jump the gun to 1.0 once we went down the FieldArray path. However, now that we have ironed that out my plan is for v12 will be 1.0. 

I am working on a roadmap now. The big item is if I can figure out a way to get #422 (`<FastField>`) fully backwards compatible with `<Field>` so we don't need to expand the API any further and can give everyone a huge perf boost fo' free. I think it is possible, but I'm not 100% certain. 

## Roadmap to 1.0:
- #422  Merge / finish `<FastField>` and optimize renders
- Add `meta` prop to existing `Field` and `FieldArray` _(this will be a breaking change if you have fields that spread props)_.
- #412 Merge tweaks `handleChange` and `handleBlur` to also optionally accept the field name as an argument instead of just the synthetic event. So you can write `<TextInput onChangeText={handleChange('firstName'} value={values.firstName} />` or on web `<input onChange={handleChange('firstName'} value={values.firstName} />`.
- Add callback / handlers for each array method in `<FieldArray>` (e.g. `handlePush`) so ppl can avoid arrow functions
- Finish docs website
  - Homepage (this is the biggest missing piece)
  - Update tooling for versioned docs
  - Update tooling for CI deployment
  - Setup DNS
- (Maybe merge #423 (big internal churn that moves to create-react-context / React 16.3 compatible context API).

## 1.0 Release process

- There will only be patches to v0.11 issued from here on out and so it will be very stable until 1.0
- Cut canary / nightly releases of v0.12 to get us through to 1.0 
- Cut multiple alpha's, beta's and then release candidates's for 1.0

## Post 1.0 Release process will follow strict semver

- Minor versions will go through alpha, beta, and rc rounds
- Patches may or may not have rc's
- Codemods will be shipped to mitigate breaking changes
