### ISSUE TITLE
Initialization of status

### ISSUE THREAD

**Issue by trentfridey** [jaredpalmer/formik#471]
## Bug, Feature, or Question?
Bug

## Current Behavior
When including a reference to `this.status.property` in a Formik inner component, where `property` is determined after `handleSubmit` is called, initially referencing `this.status.property` results in error: Cannot find property 'property' of undefined

## Desired Behavior
Reference to `this.status.property` should return `undefined` on component initialization.

## Suggested Solutions
After a few hours of digging, and looking at [this](https://codesandbox.io/s/ppnkqv78wq) CodeSandbox, the current solution is to append `this.status &&` before `this.status.property` so the conjunction short-circuits to false.

Given this is a basic JS fact of how objects evaluate, it may seem like the solution is obvious, but I found the documentation regarding how `status` is handled a little sparse. 

Maybe there could be a `initializeStatus` property for the Formik component which allows you to specify `status` on page initialization?

- Formik Version: 0.11.11
- React Version: 16.0
- TypeScript Version: N/A
- CodeSandbox Link: https://codesandbox.io/s/ppnkqv78wq
- OS: Windows 10
- Node Version: 9.5
- Package Manager and Version: npm 5.6.0

**Comment by prichodko** [comment]
I would recommend providing a default parameter for status in a destructuring. As follows: 
```js
<Formik
  render={({ status = { some: 'value' }) => ( ... )}
/>
```

Although status could be an empty object by default @jaredpalmer?

**Comment by ArtanisAce** [comment]
Had same problem tonight, and could solve it with `the status && status.property` that @trentfridey  mentioned, but I think this situation will happen and will confuse people; I agree with having an `initializeStatus` prop, or at least give info on documentation on how to avoid this error.

**Comment by georgeweiler** [comment]
Any chance of this being reopened? I ran into the same issue.

**Comment by Jbarget** [comment]
@jaredpalmer would you consider adding an `initialFormStatus`? My use case is as @agwells mentions above where we set the status of the form on `componentDidMount` but:

1. that misses the initial render
2. if we had `initialFormStatus` we wouldnt need the `setStatus` call in `componentDidMount`

Its not make or break for us but thought since we have `initialValues` and `isInitialValid` it could be a valid addition

**Comment by charlax** [comment]
Can we reopen? Would love to have an `initialStatus` property on `Formik`.

**Comment by charlax** [comment]
My use case is the following: based on some field in `status`, I would like to disable all fields. All my fields are using a light abstraction on top of `Field`. If I could set the `initialStatus`, I could retrieve `status` from inside each `Field` and set `disabled` based on its value.

Without `initialStatus`, the first render will show all the fields not being disabled...

**Comment by agwells** [comment]
Yeah, my use case is a lot like what you describe. I've got a form where sections of it start out as disabled form elements, and they can be "unlocked" for editing by clicking on a button for that section. Since this "locked/unlocked" state isn't really a form value as such, it seemed appropriate to put it into `status`.

But since writing my last comment, I've wound up putting them into `values` anyway. This was for two reasons:

1. This issue, the lack of an `initialStatus` setting. Even with the `status && status.whatever` workaround, it still caused an unnecessary extra render at the start.
2. I wanted to be able to skip validation for the locked fields, but `status` is not passed to the `validate` callback (whereas `values` is).

It still feels a little hacky, but it works pretty well. I just filter out these "status values" in my `onSubmit()` handler.

**Comment by charlax** [comment]
Indeed, that's another solution, but it does feel hacky :) You have to remember out those values inside `onSubmit`, whereas `status` was supposedly designed for the notion of "form context".

It does feel like that `status` should be passed to validate as well.

**Comment by jaredpalmer** [comment]
Added in 1.5.0

**Comment by vinodh99** [comment]
Is there a way to set the is valid manually? When I set the field value from session storage and pass the same value to the initial values, the invalid is being set to true upon error though I trigger setFieldError.
