### ISSUE TITLE
[Question] `handleChangeValue` and `touched`

### ISSUE THREAD

**Issue by apalm** [jaredpalmer/formik#49]
I'm sorry if I'm missing something, but is there a reason that `handleChangeValue`, unlike `handleChange`, sets `touched` to `true` for the field? https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L281

It seems like this "breaks" the case where you do not want to display an error until the input is blurred. https://codesandbox.io/s/v2mM8JrYn

Thanks!

**Comment by jaredpalmer** [comment]
The initial thinking was that handleChangeValue would mostly be used with custom inputs which don’t always expose legit onBlur. However I now agree that that is asymmetric. 

Instead there should be a handleBlurValue and handleChangeValue should accept an optional 3rd argument to blur.


Which brings me to my next point which is that handleChangeValue/handleBlurValue should probably be named differently as they are not really event handlerssetFieldValue and setFieldTouched but as they ar

**Comment by eonwhite** [comment]
Yeah I think you're right. We should probably rename to `setField(field, value)` and `touchField(field, value)`. The latter would set `touched`, the former wouldn't.

**Comment by jaredpalmer** [comment]
@eonwhite 

`touched` doesn't have a singular in english that makes any sense. 

What about this API?

```tsx
// values
handleChange: (e) => void
setFieldValue: (field: string, value: any, touch?: boolean)  => void
setValues: (values: V) => void

// errors
setFieldError: (field: string, msg: string) => void
setErrors: (errorsObject: FormikError) => void

// touched 
handleBlur: (e) => void
setFieldTouched: (field: string, value: boolean)  => void
setTouched: (touchedObject: FormikTouched) => void

// error
setError: (e: any) => void
```

**Comment by eonwhite** [comment]
I think the above API looks good and consistent to me.

The one I'm still a little uncertain about is the optional `touch?` parameter on `setFieldValue`. It means the component is implementing a callback signature that seems slightly idiosyncratic and specific to Formik, reducing reusability of the component in non-Formik forms.

But it feels appropriate to give the component control over when and whether to perform a touch, rather than leaving that up to the user of the component, so I think it's probably worth the tradeoff.
