### ISSUE TITLE
Formik cannot be built from source

### ISSUE THREAD

**Issue by evandavis** [jaredpalmer/formik#518]
## Bug, Feature, or Question?
I'm trying to include Formik in my bundle with Webpack. However, Formik appears to bundle `prop-types`, `invariant`, `warning`, and a few lodash modules, even if they are present in my bundle. Is this by design? I don't want to ship multiple copies of these shared libraries.

## Current Behavior
Formik bundles certain required libraries

## Desired Behavior
Formik requires these libraries as dependencies rather than bundling directly

## Suggested Solutions
Publish `src` so that Formik can be built from source.

## Additional Information
Formik is great, and I really like using it :)

---

- Formik Version: 0.11.11
- React Version: 15.3
- TypeScript Version: n/a
- CodeSandbox Link: n/a
- OS: OSX 10.12.6
- Node Version: 8.10
- Package Manager and Version: npm@5.6

**Comment by jaredpalmer** [comment]
So include src in package.json files?

**Comment by evandavis** [comment]
I think so? I am only a consumer; I haven't published anything to npm.

**Comment by prichodko** [comment]
Actually I haven't noticed it until this PR came - https://github.com/jaredpalmer/formik/pull/513, when creating ESM or CJS bundles, I believe they should **not** include any external dependencies, because bundlers can handle that.

There is a comment from @Andarist https://github.com/rollup/rollup/issues/1847#issuecomment-356644324 and also his blog post - https://developers.livechatinc.com/blog/how-to-create-javascript-libraries-in-2018-part-2/

**Comment by jaredpalmer** [comment]
Merged. Forgot to mention the issue.

**Comment by jaredpalmer** [comment]
I cut a release with the new build setup. Try `formik@next` or `formik@1.0.0-alpha.3`
