### ISSUE TITLE
High level explanation

### ISSUE THREAD

**Issue by andrewkmin** [jaredpalmer/formik#52]
Hello,
I've built a few React and React Native apps, but am still relatively new to the platform. In what cases would Formik be relevant/applicable for React Native projects? I saw in the readme that a lot of React forms are a bit over-the-top and can cause performance issues. By what factor does Formik improve rendering times/[insert tangible performance metric here]? I'm sorry if creating an issue here is an inappropriate medium for asking this question -- but would appreciate any responses. Thanks!

**Comment by jaredpalmer** [comment]
It's not that forms in and of themselves cause rendering issues, but that many other form helpers (that use context and mess with shouldComponentUpdate) can and do often run into performance problems. 

Since Formik is context free, it avoids all of those potential pitfalls while helping you with the annoying parts of forms:

- transforming state
- validation and errors
- handling submission and submission state
- staying organized and consistent across your application

Furthermore, Formik is 1.7KB min gzipped. In contrast, Redux Form is over 22 KB min gzipped.

**Comment by andrewkmin** [comment]
Thanks for the response! @jaredpalmer
