### ISSUE TITLE
submitCount is missing in type definition of formik.d.ts

### ISSUE THREAD

**Issue by leejh3224** [jaredpalmer/formik#565]
## Bug, Feature, or Question?
Bug

## Current Behavior
submitCount is missing in type definition of formik.d.ts

## Desired Behavior
it should be included in type definition

## Suggested Solutions

correct type definition for submitCount

## Additional Information
![2018-04-06 12 54 47](https://user-images.githubusercontent.com/25929117/38402779-bd896a00-3999-11e8-9c5b-6f869230bb6b.png)

---

- Formik Version:
- React Version:
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by leejh3224** [comment]
I can see "formik": "^0.11.11" in my package.json.

**Comment by ohbarye** [comment]
So my guess might be correct because:

- You may be using v0.11.11.
   - The caret (`^`) "allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple." In other words, it doesn't automatically get to use v1.x.x.
   - ref https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
-  v0.11.11 doesn't contain `submitCount`.
  
 https://github.com/jaredpalmer/formik/blob/3520bada9675985a9d024894f61eca3d82df63b6/src/formik.tsx#L55-L71

**Comment by leejh3224** [comment]
Thanks I think we can close this issue now.
