### ISSUE TITLE
Should validate() be passed props as the second argument? Documentation (kind of) suggests yes.

### ISSUE THREAD

**Issue by eugene-kim** [jaredpalmer/formik#647]
**Describe the bug**

The [docs](https://github.com/jaredpalmer/formik#validate-values-values--formikerrorsvalues--promiseany) show code that suggests that props is passed as a second argument to the `validate()` function. I'm not sure if this is intended behavior, but the [source code](https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L312) shows us that this is not the case.

Is this discrepancy a documentation error or something that was missed in the implementation? Thank you!

Screenshot of documentation:
![image](https://user-images.githubusercontent.com/955345/40282275-ca3a5e58-5c21-11e8-8fc3-dc34dba867ab.png)

Screenshot of source code:
![image](https://user-images.githubusercontent.com/955345/40282248-54f5da32-5c21-11e8-970c-bca5a576a6c2.png)

**Comment by nmaves** [comment]
I completely agree.  I just found the same inconsistency.

**Comment by erin-doyle** [comment]
Can we re-open this?  This question has not been answered and I was about to open a new Issue asking the exact same thing?  It does indeed look like the source does not pass props to validate but I don't see why it couldn't/shouldn't.  I am just guessing but I would think in `runValidateHandler` we could do:

`const maybePromisedErrors = (this.props.validate as any)(values, this.props);`

But maybe I'm missing something?

**Comment by erin-doyle** [comment]
I've been working on putting together a PR for this but it's a little more complicated than I originally though.  It looks as if `<Formik>` does not pass through any additional props to the `component/render/child` element.  So if I wanted to add a custom prop such as:

`
<Formik
    component="MyComponent"
    ...other Formik required props
    myCustomProp="someValue"
/>
`

`MyComponent` would not be passed `myCustomProp`.

So while I could just add the passing through of `this.props` to `validate` it _would_ allow for passing custom props to the `validate` function.  So `validate` would get `myCustomProp` but it could create confusion/problems if `validate` gets it but `MyComponent` doesn't.  Additionally everything that would be passed to `validate` would be the `Formik` specific props and not likely to be applicable to `validate`.

So what I _could_ do but don't feel like I can make this decision alone:
Start passing a `...rest` set of props both to the rendered `component/render/child` element, where the `Formik` specific props are removed but any custom provided props by the caller are passed through, and then also pass that same set to `validate`.

Or maybe there was a reason for locking down the passing through of additional props?

For now I'm going to post a PR that removes the reference to the `props` argument in the documentation so that it's at least consistent with the source at this time and reduces confusion caused by the expectation of functionality that isn't there.
