### ISSUE TITLE
Is there any way to set a hook that will fire if the form has failed the validation?

### ISSUE THREAD

**Issue by vovanmix** [jaredpalmer/formik#669]
I need to fire a function passed down in props if the form  (powered by formik obviously) has failed the validation after submit. It should happen only after clicking submit, not on every re-render.
What's the best approach for that?

**Comment by latviancoder** [comment]
#652 ist where similar discussion is happening. tl;dr there is no actual support for such functionality in formik, but you can achieve it by setting custom values on submit and manually submitting form.

**Comment by vovanmix** [comment]
@latviancoder how exactly can your example help triggering a function call if validation has failed?

**Comment by latviancoder** [comment]
Good question.. 

You click submit button, set custom flag in values, `submitForm`, then use custom `validate` function in which you check for your flag and call/not call your function.

The main problem is how to unset your custom flag now. It's almost like you have to use setTimeout to unset it after a short pause, because you don't have an onValuesChanged callback in formik.

Like I said, it feels hacky..
