### ISSUE TITLE
Example of How to Simulate User Interaction With Formik

### ISSUE THREAD

**Issue by machineghost** [jaredpalmer/formik#68]
One might (in Javascript tests, Selenium tests, bookmarklets, etc.) want to "manually" fill in a Formik input's value.  But, simply setting `someInput.value = 5` (obviously) won't work, as it doesn't trigger Formik's logic (and thus the old value reverts back).  I tried creating a `change` event and dispatching it on the affected `input`, but that wasn't enough either.

It would be really great if the documentation included a quick recipe for how to "simulate" (ie. create and dispatch) the event or events necessary to make Formik treat a manual change as if it had come from a user.

Thanks.

**Comment by jaredpalmer** [comment]
Sorry for the delayed response. I am going to be adding a whole guide on testing after I push #53 . Testing is hard right now with 0.7.x because of how enzyme executes synthetic simulated DOM events and the fact that Yup validation is always async. That being said, its worth checking out the [0.7.x tests](https://github.com/jaredpalmer/formik/blob/master/test/formik.test.tsx#L103) and also look at how much better things are going to get in [0.8](https://github.com/jaredpalmer/formik/blob/2fcd7976bf1f1b9ee51db3487f19313642d16e62/test/formik.test.tsx#L85) (when sync validation arrives and `submitForm()`). `submitForm()` will allow you to test your submission handler without needing to simulate (a synchronous) synthetic submit event. This means you can test an asynchronous version of your `handleSubmit` (which will call `validate` or `validateSchema`) in total isolation.

Also worth noting in the 0.8 tests, the usage of enzyme's `mount` vs. `shallow` + `dive()` may seem sometimes arbitrary. However, it has do with wanting to test the HOC's internal state and methods directly vs. indirectly via the wrapped components props. Ideally, we could test everything with `shallow` and `dive()`, but sometimes that is not possible or requires an unnecessary level of indirection.

**Comment by jaredpalmer** [comment]
Sorry, I got a little confused. 

There is nothing special about Formik, it's vanilla React. Furthermore, Formik does not add an extra DOM element around your inner-component, thus you can test your form in Selenium the same way you would test any other form.

As for getting Selenium and React setup and working together, here are some articles you may find useful: 
- [Selenium and React])https://marmelab.com/blog/2016/04/19/e2e-testing-with-node-and-es6.html)
- [Selenium + Nightwatch](https://blog.syncano.io/testing-syncano/)

Pro-tip: You can make life easier with respect to finding selectors by passing a `data-test-id` prop  DOM elements of interest. There is no penalty or accessibility issue with doing this.

**Comment by jaredpalmer** [comment]
You could also

**Comment by dcmwong** [comment]
Sorry for posting on a closed issue but I couldn't get the form filling to work.  I've put this
```
javascript: (function() { const event = new Event('input', { bubbles: true }); document.getElementById('firstName').value='test';})();
```

into a bookmark and I see the value go into the input text box but as soon as focus goes, ie. click on another field or on the body, the value is cleared.

**Comment by lvdang** [comment]
@machineghost - did you ever get this to work?

**Comment by lvdang** [comment]
@dcmwong - did this ever work for you?

**Comment by lvdang** [comment]
@machineghost  @dcmwong @jaredpalmer  - After some thoughts, when using controlled Forms like formik, etc... the component does all the logical handling and not the DOM Element.

**Comment by machineghost** [comment]
No, sorry, I moved on to another library.

**Comment by vinyoliver** [comment]
@machineghost which library are you using now?

**Comment by nilamsavani91** [comment]
Can anyone provide me an example of how to test mapPropsToValues?
