### ISSUE TITLE
Issue with field-level validation

### ISSUE THREAD

**Issue by lfalke** [jaredpalmer/formik#680]
Hi!
I'm quite new to Formik and ran into an issue using field-level validation. Not sure if it's a bug or my fault.

**Describe the bug**
When using a regular `<Field validate={...} />` the validation is never called. And when converting this Field into a custom component to include the label, validation works but it does not prevent the execution of `handleSubmit`.

**To Reproduce**
A stripped down example of both cases can be found in this CodeSandbox: https://codesandbox.io/s/l74womn8k9
I forked that from the Basics example and tried to do only minimal changes.

**Expected behavior**
The supplied validation function should be called in both cases. Also `handleSubmit` should not be called when errors exist in the form.
When having the validations in the Forms validate function (not on field-level), it works as expected. I would expect the field-level validation to behave the same.

---
- Formik Version: v1.0.0-beta.2 (but didn't work with v0.11.11 either)
- React Version: 16.4
- TypeScript Version: 16.4
- CodeSandbox Link: https://codesandbox.io/s/l74womn8k9
- OS: MacOS
- Node Version: v6.11.3
- Package Manager and Version: yarn v1.7.0

**Comment by prichodko** [comment]
`<Field validate={...} />` doesn't work, because you are overriding internal `handleBlur` and `handleChange` handlers with your props. `<Field />` manages all handlers and value automagically, you just need to provide `name`. However DX could be of course improved by putting warning into console and prevent this by switching those two lines (https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L187-L188).

Regarding second issue, you have a `isValid` flag, therefore you can disable submit button.

**Comment by lfalke** [comment]
Ah yes, thanks for your help! It's hard to understand that from the docs, so a warning message in the console would be a great improvement!

But the other question still remains. Why does a failed validation on the form prevent the execution of `handleSubmit`, but not a failed field-level validation?

**Comment by prichodko** [comment]
This seems to be related - https://github.com/jaredpalmer/formik/pull/684.

**Comment by Andreyco** [comment]
@lfalke this was fixed in #736 
Try beta 5!
