### ISSUE TITLE
Example with react-apollo

### ISSUE THREAD

**Issue by mwickett** [jaredpalmer/formik#70]
Hey there,

Wondering if anyone has used Formik along with react-apollo. I'm looking for an example of how to call a graphql mutation from formik's handleSubmit. I've looked at [recompose](https://github.com/acdlite/recompose) as a potential option.

I'm relatively new to React, so appreciate any pointers in the right direction.

**Comment by jaredpalmer** [comment]
There isn't anything special about apollo  (or redux/mobx). You end up using Formik the same way. You pass in your mutation/dispatch+action creator as a prop to the Formik-enhanced form and then call whatever you need to within Formik's `handleSubmit`. 

```
import { Formik } from 'formik'
import { graphql, compose } from 'react-apollo' // or whatevs

const handleSubmit = (payload, { props, setSubmitting, setErrors }) => {
   props.mutate(payload)  // or whatever you end up calling it
    .then(
       () => {
          setSubmitting(false) 
       }, 
       error => {
           setSubmitting(false)
           setErrors(transformMyApiErrors(error))
       }
     )
};

const MyForm = (props) => (
  <form onSubmit={props.handleSubmit}>
    ...
  </form>
)

export default compose(
   graphql(...), // your mutation or whatevs
   Formik({
      ...
      handleSubmit,
      displayName: 'MyForm',
   })
)(MyForm)
```

Now you can / might want to wrap your whatever the parent element is of the form and pass that the mutation instead. Then you don't need to use compose + formik, you can just pass in your mutation as a prop. `<MyEnhancedForm mutate={this.props.data.mutate} />`.

I have no clue how GraphQL subscriptions work. But the technique would be similar (i think). This is because the Formik HOC is stateful and it internally maps all non function / Promise props to its internal state.

**Comment by jaredpalmer** [comment]
@mwickett In answering this, I think its worthwhile to add a guide for redux and probably apollo to the docs.

**Comment by jaredpalmer** [comment]
@mwickett let me know if compose works as I expect, i haven't tried it myself. 

Another todo: check that Formik's TS types are compatible with apollo/recompose's `compose`.

**Comment by mwickett** [comment]
It does work!

Still feeling like this approach is a bit clunky, but your example really helped us (@zchsh and I) clean it up.

Here's what we've got: https://gist.github.com/mwickett/2aecfdeea40daa07d39e11922ae1fe20

**Comment by dimaninc** [comment]
don't forget to use `withFormik` instead of `Formik` in `compose()`

**Comment by rzane** [comment]
I made a little library that people might find helpful: https://github.com/promptworks/formik-apollo
