### ISSUE TITLE
1.0.0-beta.4: form `isValid` is not correctly set

### ISSUE THREAD

**Issue by codepunkt** [jaredpalmer/formik#727]
## Current Behavior
`isValid` is `false` after validation even though no errors exists on a single field form

## Steps to Reproduce
https://codesandbox.io/s/q336r5pnkw
Type in a username. The validation that is performed on the field level on change is a combination of sync `yup` and async username validation (mocking an api call checking for the existance of a username). The `isValid` prop of the form does not update according to the validation results.

## Expected behavior
When neither a sync yup validation error nor an async validation error occurs, `isValid` is true.

## Suggested solution(s)
No clue. Am i doing the validation right?

**CodeSandbox Link**:
https://codesandbox.io/s/q336r5pnkw

---

- Formik Version: 1.0.0-beta.4
- React Version: 16.3.2
- Browser and Version: Google Chrome Version 67.0.3396.99
- OS: Windows 10

**Comment by tgriesser** [comment]
The issue here is that the [`setFieldError`](https://github.com/jaredpalmer/formik/blob/7fc86da2114933b59f0176ab42a9aa07fb6a5647/src/Formik.tsx#L489) uses the  [`setIn`](https://github.com/jaredpalmer/formik/blob/master/src/utils.ts#L25-L48) helper, which does not remove undefined values, so the errors object ends up as `{errors: { username: undefined }}`. The [`isValid`](https://github.com/jaredpalmer/formik/blob/7fc86da2114933b59f0176ab42a9aa07fb6a5647/src/Formik.tsx#L552-L553) currently just checks for `Object.keys(this.state.errors).length === 0` which is incorrect.

@jaredpalmer thoughts on the best place to fix this, in the `setIn` helper, in the `setFieldError` implementation or in the `isValid` check?

Signature for `setFieldError` should also probably be changed from 
```
setFieldError = (field: string, message: string)
``` 
to 
```
setFieldError = (field: string, message: string | undefined)
```

**Comment by jaredpalmer** [comment]
I see. Yeah this is a bug (and a bad one). Would the PR to change setIn implementation to just lodash’s fp’s _set help?

**Comment by codepunkt** [comment]
`set` from `lodash` doesn't remove undefined values afaik and would also result in `{ errors: { username: undefined }}`.

**Comment by tgriesser** [comment]
Also building with any of the fp helpers, even cherry picking via `lodash/fp/set` significantly increases bundle size.

**Comment by jaredpalmer** [comment]
Exactly why I haven’t done it yet. Trying to keep bundle size in check

**Comment by codepunkt** [comment]
So, change the `isValid` implementation or the `setIn` helper?

**Comment by jaredpalmer** [comment]
We need to change setIn. isValid defininition is (almost) correct.

**Comment by codepunkt** [comment]
I attempted to fix this. Please have a look!

**Comment by vlad-zhukov** [comment]
That's a pretty nasty bug we also faced. @jaredpalmer, would be great if you could release a new version of Formik!
