### ISSUE TITLE
Formik component doesn't support mapPropsToValues prop.

### ISSUE THREAD

**Issue by dearcodes** [jaredpalmer/formik#760]
## Current Behavior
Using `Formik` component render prop doesn't execute `mapPropsToValues`

## Desired Behavior
`Formik` component render props should expose the same functionality as the `withFormik` HOC

## Suggested Solution
Adding `mapValuesToProps` to `Formik` component render prop

## Who does this impact? Who is this for?
All users

## Describe alternatives you've considered
using `withFormik`, although in my opinion this is somewhat a more intrusive implementation of Formik (adding props to parent component `propTypes`)

**Comment by cdock1029** [comment]
If you look at the Readme example of Formik component, there's a note:

> The benefit of the render prop approach is that you have full access to React's state, props, and composition model. **Thus there is no need to map outer props to values**...you can just set the initial values, and if they depend on props / state
          then--boom--you can directly access to props / state.

If you have a component that wraps 
```<Formik../>```  then you can just initialize `initialValues` with your props. Along with `enableReinitialize={true}` you can update the Form with new props...

**Comment by dearcodes** [comment]
@cdock1029 Thanks!

**Comment by theweiweiway** [comment]
I think this is related to a problem I'm having, I'm trying to read prop values that I'm passing in from a parent, which is then used with a react-select component that has similar code to https://codesandbox.io/s/73jj9zom96. I am able to read the props, but then my react-select component doesn't work at all.
``
class Post1 extends React.Component {

  render() {
    const { classes } = this.props;
    return (
      <div>
        <Formik  
          enableReinitialize={true}
          initialValues={{
            category: this.props.initValues.category, 
            type: [], 
          }}
...
``

If I use: 
``
          mapPropsToValues={props => ({ 
            category: this.props.initValues.category, 
            type: [], 
          })} 
``
instead of ``enableReinitialize`` and ``initialValues``, my initial props don't get read at all. Could someone point me in the right direction?

**Comment by vinodh99** [comment]
@jaredpalmer  Using enableReinitialize is abruptly updating the form values and causing a rerender on the component. For example a dropdown component is rerendered upon selecting a value and if initialValues is updated due to this onChange event. I had to fix this by switching back to withFormik. As I never really needed to use Formik component, it worked for me. It would be nice to have mapPropsToValues.
