### ISSUE TITLE
Why are empty strings mapped to undefined before validation?

### ISSUE THREAD

**Issue by tamlyn** [jaredpalmer/formik#805]
I'm wondering what the reason for this code is

https://github.com/jaredpalmer/formik/blob/955b6d3624630a92c7e840dc39b13e4f5612278f/src/Formik.tsx#L663-L668

I want to have an input which is either null (i.e. hidden) or a string but cannot be an empty string. 

```js
yup
    .string()
    .notOneOf([''], 'Required')
    .nullable()
```

This doesn't work if the field in question is at the top level of the form due to the coercing of `''` to `undefined` which makes yup ignore the field if its value is empty. But what's even more unexpected is that it *does* work when the field is nested in a sub object since the coercion is not recursive.

I'm sure there's a good reason for this behaviour and I would like to understand it.

**Comment by jaredpalmer** [comment]
I forgot why. @jquense is there a good way to do this in Yup land?

**Comment by jaredpalmer** [comment]
Ian (eonwhite) is on his honeymoon right now and I don't want to ping him. He wrote that part initially IIRC. He'll be back in a week or so.

**Comment by pytkin** [comment]
@jaredpalmer do you have some progress with this issue guys? I'm stuck on it.

If i'm correct he trying to check that `key` is exist on `values` array. You need to replace `values[key] !== ''` with `typeof values[key] !== 'undefined'`, but i'm not sure, because I don't know what structures contains in this arrays.

**Comment by eonwhite** [comment]
You are right, this does date back to the original proto-Formik code from spring '17! The reason as @jquense guessed, is to force Yup to skip validation on optional fields that are empty.

The fact that it does not apply this rule to sub-objects as @tamlyn noticed is, I think, an oversight and a bug. Whatever the behavior is, it should probably be consistent between top level or in sub-objects.

I could see an argument that this behavior is too magical altogether, and maybe we should consider a breaking change to remove it. But (beyond compatibility breakage) it would come at the cost of making some validations for optional fields harder to express, since it would force the user to explicitly check for the empty-string case in many situations.

For what @tamlyn is trying to do (conditionally validate a field depending on some other form state), there are some clearer ways to express this idea -- for example using Yup's `when()` to conditionally apply the required validation.

**Comment by byrekt** [comment]
Hello, I ran into an issue related to this yesterday. I have a component `<Payment />` that can have any number of child components of various types related to form fields. Something like:
```javascript
<Payment>
  <FirstName />
  <LastName />
  <CreditCardNumber />
  <ExpirationDate />
</Payment>
```
The Yup schema makes heavy use of `yup.lazy` to ensure that the `initialValues` contains the field before trying to validate it. This code setting things to `undefined` is turning all the empty string values into `undefined` so that even though I'm setting the values to empty strings in `initialValues` the fields aren't getting validated until a value is entered. So even though all of these fields are required it is allowing an empty value for each of them since my schemas for the fields look something like:
```javascript
// Should only validate the number if the creditCardNumber is present in initialValues of Formik
creditCardNumber: yup.lazy(value => {
  // This is my problem right here. The Formik code is setting all empty strings
  // to undefined so this wont work.
    if (value !== undefined) {
      return creditCardNumber // reference to the schema for the field
    }
    return yup.mixed().notRequired()
  })
```
So I think a workaround for my use case would be to nest all of these fields inside a sub-schema(`{ payment: { creditCardNumber}}`, but I really don't like how ugly that makes the code for the react components. Thoughts?

**Comment by jquense** [comment]
work to cover this use-case more directly and broadly is being discussed here: https://github.com/jquense/yup/issues/298

**Comment by belt-basya** [comment]
I am also facing the same problem! Does anyone have a solution?

**Comment by dKustura** [comment]
I too came across a use-case where I need to use Yup.test for custom validation of a complex values and this seems to be a big problem. Any help is appreciated.

**Comment by fwolff** [comment]
I had the same problem with ```Yup.string().defined()``` and Formik.

My current workaround is to use ```Yup.string().default('').defined()```: Formik changes ```''``` to ```undefined``` before passing in the value to Yup, Yup then changes ```undefined``` back to ```''``` before validation.

Very ugly of course...

**Comment by lexa0303** [comment]
Any updates on this? Can we have a feature to disable that transformation at all, or provide our own `prepareDataForValidation` function? I need to make validation that allows undefined but not allow empty string.

**Comment by johnrom** [comment]
@lexa0303 you should open a new issue and reference this one because this one is a bit of a necro. I think we should remove this legacy functionality in v3.

**Comment by zsidnam** [comment]
Ironically, I found out about this behavior because I tried refactoring a form to use react-hook-form instead of Formik, and all of my (non-required) number fields triggered unwanted type errors when validation ran with those fields left blank. Turns out Formik was handling those empty string values all along! I now wish that yup had a global option to enable that behavior. Looks like I need to go add a bunch of transforms for those optional number fields. (If anyone has run into this and found a great solution, I'd love to hear it!)

**Comment by AminDannak** [comment]
> I had the same problem with `Yup.string().defined()` and Formik.
> 
> My current workaround is to use `Yup.string().default('').defined()`: Formik changes `''` to `undefined` before passing in the value to Yup, Yup then changes `undefined` back to `''` before validation.
> 
> Very ugly of course...

This solved the issue with `Yup.string()` cases, but if you're using `Yup.string().oneOf()`, and `''` is not a member of the array you pass to `oneOf()` it's gonna lead to error.

**Comment by nikolaykrashnikov** [comment]
try to add string().default(undefined)

**Comment by DarkPage** [comment]
I love Formik but with trears. T_T. I really need the origin value, i don't want the empty string changed to undefined.

Formik@2.2.9 function prepareDataForValidation:
`data[key] = values[key] !== '' ? values[key] : undefined;`

**Comment by sansarj17TIF** [comment]
Did anyone found a solution for it ?? Do we have a prop we can pass to disable the transformation ??
