### ISSUE TITLE
Form submission of invalid forms

### ISSUE THREAD

**Issue by julian-r** [jaredpalmer/formik#815]
## Current Behavior
Submission is only possible if the form is valid.
## Desired Behavior
It might sound obscure, but sometimes you want to submit invalid forms as well. E.g. Drafts of something.

## Suggested Solution
Add property to enable submission of invalid forms.

**Comment by julian-r** [comment]
#816

**Comment by prichodko** [comment]
Then why you need a validation at the first place?

**Comment by julian-r** [comment]
To still give the user feedback if everything is fine.  (Th form stays open or touched fields)

Yes, true, thats how I do it currently. Just a suggestion, maybe I am not the only one :)

**Comment by prichodko** [comment]
I will close it for now, may re-open in a future if needed.

**Comment by OfficerHalf** [comment]
I've actually come up to this situation. It's not the exact same scenario, but the same feature would be needed to properly support it:

- I have a form that is a list of new users to be added. This can be any number of users. 
- Each user has first name, last name, email, country. If any of these are blank, that user is invalid

Then the customer decided they didn't want the operation to be atomic, instead all valid users should be submitted, and removed from the FieldArray, all invalid should stay to be fixed. I don't particularly like this idea (and said as much), but it is what I'm being paid to do. Right now my plan is to re-implement visual validation as part of onBlur/onChange, form level validation in onSubmit. But a simple toggle that would call submit even if not everything was valid would be very useful in not having to do any of that. 👍

**Comment by workforbala** [comment]
i am having same scenario where user can allow to save invalid forms but we need to show form is invalid to user. since its huge form takes time to solve all issue we allow user to submit it. is there any way to do so ?

**Comment by crhistianramirez** [comment]
This is worth considering. I'm working on a very large form that is broken up across various tabs and while I have indicators showing which field is required it is still possible a user may miss one since the error message and highlighting isn't shown until the input is dirty. We'd prefer to allow the user try to submit the form so that we can then dirty all fields and bring attention to the unsubmitted fields, possibly even throw up a dialog indicating which field is missing. 

This is a lot less frustrating then a user being unable to submit a form, and not knowing why they can't submit it. Exacerbated by the sheer size of the form.

**Comment by noamkfir** [comment]
I know this is an old issue but I think it's an important one.

Form validation has several purposes. The main purpose is obviously preventing bad input, but another really important one is clearly explaining problems to the user.

Preventing bad input is clearly important and the usual expected behavior is that invalid forms shouldn't be submitted. But that's not always the case. There are numerous cases where you need to be able to submit invalid forms, including these:
- Lengthy forms that might take hours, days, or longer to complete. Forms like these often have to store intermediate state before they're finally "submitted".
- Forms with complex state, like forms that have (plain, rich, or whatever) text fields, dependent fields (e.g., country > state > city), and so forth.
- Forms designed to support business requirements that place value on "invalid" states, like abandoned carts.
- Forms designed for complex processes, such as approval processes where multiple people might interact with the same form. For example, a form to create a quote for a deal could be drafted by one person who fills out some fields, priced by a manager, and approved by a director, could have fields that are technically "invalid" or "valid" depending on the user or step of the process.
- Some forms can become invalid when the user isn't interacting with them. Consider a form that lets you upload a photo of a government id. When the user upload a photo, the form becomes valid. But if the website owner reviews the image and determines that it's not suitable, they could invalidate the field and require the user to submit a new one.
- And I'm sure there are plenty more that don't come to mind just now.

Programmers also tend to rely on client-side form validation even though it's well known that the server (where there is one) should perform its own validation as well. Client-side validation isn't intended to protect the database (or the server) but rather the user.

The point is that even if most applications reject most invalid forms, others either store and keep track of the validation state, or, in more advanced use cases, have clearly defined behaviors for different validation states.

So why do we need validation if not to prevent submission? Validation provides valuable communication with the user. It helps guide the user and ensure that the end result is correct, even if we save the intermediate invalid states. And it helps ensure correctness even if validation is achieved after a lengthy or complicated process.

Validation is a business concern, not a technical constraint, so it could have different meanings in different contexts and it could be handled in many different ways. Formik shouldn't force a specific interpretation of what is "valid" and how it should affect the form.

A single boolean prop to allow submission of invalid forms would go a long way to solving this. Another possibility is a function or promise that return a boolean, for more flexibility.
