### ISSUE TITLE
Form Displays Wrong Default Value

### ISSUE THREAD

**Issue by charliefriedberg** [jaredpalmer/formik#818]
```js
<Field component='select' name='filterBy'>
    <option disabled selected>
        Select Role
    </option>
    <option value=''>None</option>
    <option value='a'>A</option>
    <option value='b'>B</option>
    <option value='c'>C</option>
</Field>
```

For some reason, `A` is the default selected option, not `Select Role`. I'm using the Formik like this:
```js
<Formik 
validate={...}
submit={...}
...
render={({stuff}) => (
    <Form>
     Fields Go Here
    </Form>
)}
/>
```

Am I doing something wrong, or is this bug.

## Versions
 * formik: 1.0.2
 * next: 6.1.1
 * react: 16.4.2

**Comment by prichodko** [comment]
Please don't ignore an issue template, it helps other people to help you faster.

Select inputs are handled differently in React, instead of setting a `selected` property on a option, pass a `value` prop to the `<select>` tag. More info in the official docs - https://reactjs.org/docs/forms.html#the-select-tag

I think this should fix the issue, because Formik then correctly passes `value` to the input.

**Comment by charliefriedberg** [comment]
thank you @prichodko. this worked.

Weird because when i wasn't using formik `<option disabled selected>` worked.

Apologies for not following the format. Will do so in the future.

**Comment by ShriduttPatel121** [comment]
I think you can set it in initialValues ( while initializing the initialValues of the Formik component itself). It worked for me.
` <Formik
                initialValues = {{
                    name : '',
                    email : '',
                    password : '',
                    isManager : 'true'
            }} >
     {yourForm} 
</Formik>`
