### ISSUE TITLE
How to validate formik & Yup validation with file type and size ?

### ISSUE THREAD

**Issue by saurabh147sharma** [jaredpalmer/formik#926]
Hi

I couldn't find any doc for file upload validation in formik and yup. Please help me how to do that ?

**Comment by jaredpalmer** [comment]
Yup doesn’t handle this. You can use your own validation function at either the form or field-level.

**Comment by alecchisi** [comment]
After following this tutorial to integrate a file upload component in my form
https://hackernoon.com/formik-handling-files-and-recaptcha-209cbeae10bc
I've been able to test file size and type like this: 
`iconFile: Yup.mixed()
            .test('fileSize', "File Size is too large", value => value.size <= FILE_SIZE)
            .test('fileType', "Unsupported File Format", value => SUPPORTED_FORMATS.includes(value.type) )`

**Comment by alecchisi** [comment]
Try this: 
https://codesandbox.io/s/4wrrx8qok0

**Comment by Cuxs** [comment]
@alecchisi  When I do
```javascript
        yup.object().shape({
        file: yup.mixed().required('A file is required')
        .test('fileFormat', 'PDF only', (value) => {
          console.log(value); return value && ['application/pdf'].includes(value.type);
        }),
```
In my console only appears ```C:\fakepath\Filename.pdf``` not the file itself. My rendered input is

```html
<input
    id="
    name="file"
    type="file"
    onChange={handleChange}
    className={
         errors.password && touched.password
         ? 'form-control is-invalid'
         : 'form-control'
     }
/>
```

What could be possibly wrong?

**Comment by alecchisi** [comment]
That is correct, because the html5 `input` tag like that only contains the filename (it is considered a text input). You should code a component like the one in my sandbox (or in the tutorial I've linked upper in this thread), and use the formik <Field> component to embed and expose correctly the corresponding object.

**Comment by Cuxs** [comment]
@alecchisi Ahh, cool. Thanks!

**Comment by gaurav-pantelwar** [comment]
@alecchisi What if I want file to be an optional and also if any file selected validate file size and file type?

**Comment by ZephSibley** [comment]
I refactored alecchisi's example into something more simple and functional https://otxz6.csb.app/

**Comment by mariselvanm** [comment]
@ZephSibley While updating the Formik and Yup libraries in your code sandbox it just stopped working. Can you please look at it? Because I wasted a lot of time on this. So, if you update this it'll help people who are looking for the same kind of solution.

**Comment by monsieur-z** [comment]
Hi, I'm running into the same issue as @mariselvanm, I believe. I've isolated it in a sandbox.

With version 1.5.8 of Formik, I'm able to see the file size in the console when I select a picture: https://codesandbox.io/s/yup-formik158-86xny

In this sandbox, I've just updated the version of Formik to 2.0.3, and I've got `undefined` instead of the file size: https://codesandbox.io/s/yup-formik203-14vlq

**Comment by mariselvanm** [comment]
@jaredpalmer Is there any way we can validate using `validate` and `validateScheme` in a single form?

**Comment by jaredpalmer** [comment]
@mariselvanm yes you can use both. I would not suggest it.

**Comment by dorklord23** [comment]
> After following this tutorial to integrate a file upload component in my form
> https://hackernoon.com/formik-handling-files-and-recaptcha-209cbeae10bc
> I've been able to test file size and type like this:
> `iconFile: Yup.mixed() .test('fileSize', "File Size is too large", value => value.size <= FILE_SIZE) .test('fileType', "Unsupported File Format", value => SUPPORTED_FORMATS.includes(value.type) )`
> 
> where FILE_SIZE is a numeric constant and SUPPORTED_FORMATS is an array of valid image type strings ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']

@alecchisi I follow your example but variable `value` in the callback is `null` :/

**Comment by alex-r89** [comment]
Hi there,

Sorry to comment on a closed issue but I think this may be useful to some people:

The solution posted by @alecchisi  works very well for file uploads **IF** the field is required, however this will not work if the field is not required - for example if a file upload is optional for the user.

In this case, the solution will fail because the default value for the `file` (`null` in my case) will not pass on either `value => value.size <= FILE_SIZE` or `value => SUPPORTED_FORMATS.includes(value.type)`. 

In order to fix this for non required file uploads, I have the following yup scheme:

```js
const validationSchema = object().shape({
  file: mixed()
    .test('fileSize', 'File too large', (value) => value === null || (value && value.size <= FILE_SIZE))
    .test(
      'fileFormat',
      'Unsupported file type',
      (value) => value === null || (value && SUPPORTED_FORMATS.includes(value.type))
    )
})


  const formik = useFormik({
    initialValues: {
      file: null
      // More values here
    },
// More code here
```

Just to also note, substituting this for `mixed().nullable(true)` will not work because it will still fail on the tests.

**Comment by caiosamarone** [comment]
@alex-r89 what if i want to check the height and the width of the image? Do you know how can I do this?

**Comment by sven5** [comment]
what about with multiple files?

**Comment by mihailsitnic** [comment]
Use validation in a separate file:

`
const { errors } = props

function isEmpty(obj) {
    return Object.keys(obj).length === 0
}

const isValid = isEmpty(errors)
`

**Comment by thinkDigitalZw** [comment]
This is 2021, so I have assumptions something changed about that as the current implementation. 

The code below when I console log the value object it returns VALUE C:\fakepath\ADVERT-PROCUREMENT-MANAGER-GMB.pdf

If I console log `value?.size <= FILE_SIZE` it returns false.

`
        .test(
          "fileSize",
          "File too large",
          (value) => value && value.size <= FILE_SIZE
        )`

What I want to achieve is simple.

1. Get the actual numeric file size
2. Know how to interpret the FILE_SIZE numeric e.g value of 1MB, 1GB etc

**Comment by SinaBYR** [comment]
> After following this tutorial to integrate a file upload component in my form
> https://hackernoon.com/formik-handling-files-and-recaptcha-209cbeae10bc
> I've been able to test file size and type like this:
> `iconFile: Yup.mixed() .test('fileSize', "File Size is too large", value => value.size <= FILE_SIZE) .test('fileType', "Unsupported File Format", value => SUPPORTED_FORMATS.includes(value.type) )`
> 
> where FILE_SIZE is a numeric constant and SUPPORTED_FORMATS is an array of valid image type strings ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']

I was facing the same problem. Thank you!

**Comment by quyle92** [comment]
For anyone received `"C:\fakepath\Filename.pdf`" as value in yup validation function, it is because yup was taking `e.target.value `as param in `test validator`. So in order to retrieve the whole `file object` at `test validator,` you need to set field value explicitly at native `onChange` event like so:
```
<input
    type="file"
    ...
    onChange={(e) => {
           form.setFieldValue(field.name, e.target.files[0]); 
    }}
    
/>
```
Note:  Apart from `handleChange`, `setFieldValue() `also trigger validation. Ref: [https://formik.org/docs/guides/validation#when-does-validation-run](https://formik.org/docs/guides/validation#when-does-validation-run)

**Comment by Khaan25** [comment]
> ```js
> .test('fileFormat', 'PDF only', (value) => {
>           console.log(value); return value && ['application/pdf'].includes(value.type);
>         })
> ```

Replace line with following:  value.type.includes('application/pdf');

**Comment by carmel26** [comment]
**The subject must be even close but the solution which i found was that simple**
First you declare setFieldValue in your declarations
`const { 
        values, 
        errors, 
        touched, 
        isSubmitting, 
        setFieldValue,
        handleBlur,  
        handleChange, 
        handleSubmit
      } = useFormik({
  
      initialValues: {   
        evidence_for_accreditation_at_national_level : "",  
      },
  
      validationSchema : ApplicationSchemasValidation,
      onSubmit,
    });
   `
Here ApplicationSchemasValidation it is a Schemas which i declared in another file for my validations
**And in your input just add it and remove handleChange event in onchange function**

`<input 
                                    className={`
                                    ${errors.evidence_for_accreditation_at_national_level && touched.evidence_for_accreditation_at_national_level ? "input-error" : ""}`} 
                                    id="evidence_for_accreditation_at_national_level" 
                                    type="file"  
                                    accept="application/pdf" 
                                    onChange={(event) => {
                                        setFieldValue("evidence_for_accreditation_at_national_level", event.currentTarget.files[0]);
                                      }} 
                                    onBlur={handleBlur} />
                                    {errors.evidence_for_accreditation_at_national_level && touched.evidence_for_accreditation_at_national_level ? <p className="text-red-500 text-xs italic">{errors.evidence_for_accreditation_at_national_level}</p> : ""}`

**Hope it will help someone**
