### ISSUE TITLE
Input loosing focus when used with Formik  react-number-format

### ISSUE THREAD

**Issue by bernatfortet** [jaredpalmer/formik#958]
## Current Behavior
- Using react-number-format as input
- input looses focus after each keystroke

## Steps to Reproduce
Here's a code sandbox to illustrate the issue. Just fill in the inputs and you'll see the effect
https://codesandbox.io/s/v0o02wjyl5

## Expected behavior
Keystrokes don't provoke the input to loose focus

---

- Formik Version: 1.3.1
- React Version: 16.5.0
- Browser and Version: using codesandbox

**Comment by jaredpalmer** [comment]
I don't think this issue is actually with Formik, but with react-number-format. It seems that onValueChange and customInput cause this behavior when they are used together. 

Related issue on react-number-format: https://github.com/s-yadav/react-number-format/issues/67

I made a sandbox to demonstrate this nuance both with and without Formik. 
https://codesandbox.io/s/ppo1kvlwpx
