### ISSUE TITLE
<Field  name="name" /> not reseting if not initialValues passed

### ISSUE THREAD

**Issue by PetroPavlenko** [jaredpalmer/formik#979]
## Current Behavior

1. reset form 
2. Field with only name and type not  reseted

## Steps to Reproduce
1. type text in ``<Field  name="name" />`` or in `<Field  type="email" name="email" />``
2. reset form

## Expected behavior
should be changed to empty string

## Suggested solution(s)
pass in HTML value empty string if no component, no render, etc passed

---

- Formik Version: 1.3.1
- React Version: 16.5.2
- Browser and Version: Chrome
- OS: OS X
- Node Version: 10.7.0
- Package Manager and Version: Yarn 1.10.1

**Comment by jaredpalmer** [comment]
Reset will only work if you pass initialValues.

**Comment by PetroPavlenko** [comment]
So, Is it more like feature request?

**Comment by jaredpalmer** [comment]
In order to safely work with React Fiber, we can no longer register a Field in componentWillMount (which would solve for this problem). This means we can’t guess the shape of your form values ahead of first render without initialValues present. Kinda annoying, but it’s just how React works. 

However, reset happens after initial render, so this _could_ be awkwardly solved if we gave Field a default value of an empty string and then registered it with the parent Formik as an initialValue. Unfortunately, this would create another problem: knowing if it’s the first true render. If we do this, it would trigger on every single componentDidMount. However, that would alter initialValues whenever a Field is rendered conditionally. As you can imagine, this opens up a bunch of odd cases with dynamic forms that add and remove fields. 

Instead, Field doesn’t have a default value so you always get a React uncontrolled Input error if you forget about initialValues. This matches how React works. Open to alternatives, b

**Comment by PetroPavlenko** [comment]
As an alternative
Can handle undefined on Field value more properly 

To fix my case: it would be nice to check for 'undefined' value while passing it in input
So if no render, etc, Field can check value for undefined while passing it in Input. Or we can add special property for it

**Comment by jaredpalmer** [comment]
While this would indeed fix that error message, it doesn’t solve your issue since a default value on Field still can’t be communicated as a part of initialValues in the parent Formik.

**Comment by jpserrett** [comment]
@jaredpalmer I'm loading initalValues from an API response, and if the value of a Field is null, I don't get that property in my JSON. So this means that my initialValues doesn't have that property defined at all. If I understand what you are saying correctly, that would also cause this same issue, correct? The data would not reset to an empty string on calling reset?
