### ISSUE TITLE
Add default component to <Filed />

### ISSUE THREAD

**Issue by PetroPavlenko** [jaredpalmer/formik#982]
## Current Behavior
if change `<input value="the oldest" />` to `<input value={undefined} />` using `<Field />`
in dom we still can see  "the oldest" 

## Desired Behavior
It should be handled in component or render, etc

## Additional context
html doesn't handle undefined correctly, and formik should handle that

**Comment by Saifadin** [comment]
How do you change the value? Can you provide the code?

**Comment by PetroPavlenko** [comment]
@Saifadin check #979

**Comment by Saifadin** [comment]
I know understand that. If you pass undefined as a value and then a value, React will throw an error because you go from uncontrolled to controlled. That is not a good way of handling the state of your inputs. you should always have the defaultValue as something other then undefined or null. So if it is a text input. It should be an empty string.

If I misunderstood your question, correct me 😄

**Comment by jaredpalmer** [comment]
This is not how React works. You are changing from controlled to uncontrolled and all bets are off.
